#!/bin/bash
# PORTMASTER: offtheroad, Off The Road.sh
# Off The Road — generated by nxbootstrap 0.6.32.
NXBOOTSTRAP_FINISHED=0
NXBOOTSTRAP_ABORTING=0
NXBOOTSTRAP_EARLY_LOG_ACTIVE=1
NXBOOTSTRAP_LAUNCHER_DIR=""
NXBOOTSTRAP_HEALTH_FILE=""
nxbootstrap_finish() {
  [ "$NXBOOTSTRAP_FINISHED" = 0 ] || return 0
  NXBOOTSTRAP_FINISHED=1
  if command -v pm_finish >/dev/null 2>&1; then pm_finish || true; fi
}
nxbootstrap_write_early_log() {
  local status=$1 log_dir log_path
  [ "$NXBOOTSTRAP_EARLY_LOG_ACTIVE" = 1 ] && [ "$status" -ne 0 ] 2>/dev/null || return 0
  for log_dir in "${GAMEDIR:-}" "$NXBOOTSTRAP_LAUNCHER_DIR" \
    "${XDG_RUNTIME_DIR:-}" "${TMPDIR:-/tmp}"; do
    [ -n "$log_dir" ] && [ -d "$log_dir" ] && [ ! -L "$log_dir" ] || continue
    log_path="$log_dir/offtheroad-launcher-error.$$.log"
    if (umask 077; set -C; printf '%s\n' \
      '== Off The Road | nxbootstrap 0.6.32 | pre-runtime failure ==' \
      "status=$status pid=$$" "launcher=${BASH_SOURCE[0]:-$0}" \
      "game_dir=${GAMEDIR:-unresolved}" "cfw=${CFW_NAME:-unknown}" > "$log_path") 2>/dev/null; then
      printf 'nxbootstrap: pre-runtime failure; log=%s\n' "$log_path" >&2
      return 0
    fi
  done
  printf 'nxbootstrap: pre-runtime failure; no writable diagnostic path\n' >&2
}
nxbootstrap_on_exit() {
  local status=$1
  # Fallback instance lock (firmwares without flock): released here, on the
  # one EXIT path every outcome funnels through. NUNCA usar o nome
  # NXBOOTSTRAP_LOCK_DIR: ele e' o diretorio REAL do lock, compartilhado
  # entre instancias -- apaga-lo aqui ja' quebrou o teste de contencao.
  if [ -n "${NXBOOTSTRAP_FALLBACK_LOCK_DIR:-}" ]; then
    rm -rf "$NXBOOTSTRAP_FALLBACK_LOCK_DIR" 2>/dev/null || true
  fi
  if [ -n "${NXBOOTSTRAP_HEALTH_FILE:-}" ]; then
    rm -f -- "$NXBOOTSTRAP_HEALTH_FILE" \
      "$NXBOOTSTRAP_HEALTH_FILE.tmp.$$" 2>/dev/null || true
  fi
  nxbootstrap_write_early_log "$status"
  nxbootstrap_finish
  return "$status"
}
nxbootstrap_install_exit_trap() {
  trap 'nxbootstrap_on_exit $?' EXIT
}
nxbootstrap_abort_before_game() {
  local abort_status=$1
  [ "$NXBOOTSTRAP_ABORTING" = 0 ] || return 0
  NXBOOTSTRAP_ABORTING=1
  echo "== aborted before game start (status $abort_status) =="
  nxbootstrap_finish
  exit "$abort_status"
}
nxbootstrap_install_early_traps() {
  trap 'nxbootstrap_abort_before_game 130' INT
  trap 'nxbootstrap_abort_before_game 143' TERM
  trap 'nxbootstrap_abort_before_game 129' HUP
}
nxbootstrap_install_exit_trap

# A signal before the game starts (mapper/extraction can take seconds) must
# still hand the screen back to the frontend instead of dying by default.
nxbootstrap_install_early_traps

# The EXIT trap is deliberately live before path discovery, PortMaster, controls
# or any other command that can fail.  Resolve the visible launcher only now.
NXBOOTSTRAP_LAUNCHER_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd -P) || \
  NXBOOTSTRAP_LAUNCHER_DIR=""


XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
# Language / Idioma (supported / suportados: en).
# Edit only this value; adapters opt in through nxport.json.
GAME_LANGUAGE="en"
case "$GAME_LANGUAGE" in
  auto|en) ;;
  *) GAME_LANGUAGE="auto" ;;
esac
NXPORT_LANGUAGE=${NXPORT_LANGUAGE:-$GAME_LANGUAGE}
case "$NXPORT_LANGUAGE" in
  auto|en) ;;
  *) NXPORT_LANGUAGE=$GAME_LANGUAGE ;;
esac
NXBOOTSTRAP_LANGUAGE=$NXPORT_LANGUAGE
export NXPORT_LANGUAGE


# PortMaster publishes the integrated handheld stick count as ANALOGSTICKS;
# some CFW adapters use ANALOG_STICKS. Keep it as a validated host hint only:
# per-controller SDL bindings remain the authority for actual capabilities.
NXBOOTSTRAP_ANALOG_STICKS_HINT=""
unset NXINPUT_ANALOG_STICKS_HINT

# Safe CFW identity is diagnostic/mod-selection context only, never a quirk.
nxbootstrap_observe_cfw_name() {
  local candidate=""
  case "${CFW_NAME-}" in *[!A-Za-z0-9._-]*|'') unset CFW_NAME ;; *) return 0 ;; esac
  if [ -n "${HOME:-}" ] && [ -f "$HOME/.config/.OS" ] && \
     [ ! -L "$HOME/.config/.OS" ]; then
    IFS= read -r -n 65 candidate < "$HOME/.config/.OS" || true
  fi
  [ "${#candidate}" -le 64 ] || candidate=""
  case "$candidate" in *[!A-Za-z0-9._-]*|'') candidate="" ;; esac
  # dArkOSRE omits .OS: require two independent regular firmware artifacts.
  if [ -z "$candidate" ] && \
     [ -f /boot/arkos4clone-uboot.dtb ] && [ ! -L /boot/arkos4clone-uboot.dtb ] && \
     [ -f "/opt/system/Advanced/Backup dArkOS Settings.sh" ] && [ ! -L "/opt/system/Advanced/Backup dArkOS Settings.sh" ]; then
    candidate=dArkOSRE
  fi
  # ArkOS/TheRA/RetroOZ publish their identity in the plymouth title (same
  # source as PortMaster's device_info.txt); ELEC/JELOS/ROCKNIX/muOS/Knulli in
  # os-release OS_NAME/NAME. Plain ArkOS used to log cfw=none without .OS.
  local pfile=/usr/share/plymouth/themes/text.plymouth
  if [ -z "$candidate" ] && [ -f "$pfile" ] && [ ! -L "$pfile" ]; then
    candidate=$(grep -a -m1 '^title=' "$pfile" 2>/dev/null | cut -d= -f2- | cut -d' ' -f1 | tr -cd 'A-Za-z0-9._-' | cut -c1-64)
  fi
  if [ -z "$candidate" ] && [ -f /etc/os-release ] && [ ! -L /etc/os-release ]; then
    candidate=$(grep -a -m1 '^OS_NAME=' /etc/os-release 2>/dev/null | cut -d= -f2- | tr -d '"' | cut -d' ' -f1 | tr -cd 'A-Za-z0-9._-' | cut -c1-64)
    [ -n "$candidate" ] || candidate=$(grep -a -m1 '^NAME=' /etc/os-release 2>/dev/null | cut -d= -f2- | tr -d '"' | cut -d' ' -f1 | tr -cd 'A-Za-z0-9._-' | cut -c1-64)
    case "$candidate" in Debian|Ubuntu|Linux|Buildroot) candidate="" ;; esac
  fi
  case "$candidate" in *[!A-Za-z0-9._-]*|'') candidate="" ;; esac
  [ -n "$candidate" ] && CFW_NAME=$candidate
}
nxbootstrap_observe_cfw_name
# Find a real control.txt instead of stopping at the first empty PortMaster
# directory. The roots mirror the supported PortMaster/CFW layouts; the first
# valid regular control file keeps precedence.
controlfolder=""
# 23/08/2026: lista COMPLETA, espelho de nxbootstrap_default_portmaster_roots
# (a 0.5.1 conhecia 33 raizes e o launcher publicado so' 22 -- Miyoo/spruce,
# RetroDECK e cartoes com "Ports" maiusculo caiam no fallback sem controles).
# test-safety-static.sh trava a igualdade dos dois conjuntos.
NXBOOTSTRAP_PM_ROOTS=(
  "$(dirname "$(readlink -f "$0")")/PortMaster"
  "/opt/system/Tools/PortMaster" "/opt/tools/PortMaster"
  "$XDG_DATA_HOME/PortMaster"
  "${HOME:-/tmp}/.var/app/net.retrodeck.retrodeck/data/PortMaster"
  "/storage/.config/PortMaster"
  "/var/data/PortMaster" "/PortMaster"
  "/roms/tools/PortMaster" "/roms2/tools/PortMaster"
  "/storage/roms/ports/PortMaster" "/storage/roms/Ports/PortMaster"
  "/roms/ports/PortMaster" "/roms/Ports/PortMaster"
  "/roms2/ports/PortMaster" "/roms2/Ports/PortMaster"
  "/userdata/roms/ports/PortMaster" "/userdata/roms/Ports/PortMaster"
  "/userdata/system/.local/share/PortMaster"
  "/mnt/ports/PortMaster" "/mnt/Ports/PortMaster"
  "/mnt/mmc/MUOS/PortMaster" "/mnt/mmc/ports/PortMaster"
  "/mnt/mmc/Ports/PortMaster"
  "/mnt/mmc/roms/ports/PortMaster" "/mnt/mmc/ROMS/ports/PortMaster"
  "/mnt/SDCARD/Apps/PortMaster/PortMaster"
  "/mnt/sdcard/Roms/.portmaster/PortMaster"
  "/mnt/sdcard/MIYOO_EX/PortMaster"
  "/mnt/sdcard/ports/PortMaster" "/mnt/sdcard/Ports/PortMaster"
  "/mnt/sdcard/roms/ports/PortMaster" "/mnt/sdcard/ROMS/ports/PortMaster"
)
for NXBOOTSTRAP_PM_CANDIDATE in "${NXBOOTSTRAP_PM_ROOTS[@]}"; do
  [ -f "$NXBOOTSTRAP_PM_CANDIDATE/control.txt" ] && \
    [ ! -L "$NXBOOTSTRAP_PM_CANDIDATE/control.txt" ] || continue
  NXBOOTSTRAP_PM_REAL=$(readlink -f "$NXBOOTSTRAP_PM_CANDIDATE" 2>/dev/null) || continue
  [ -d "$NXBOOTSTRAP_PM_REAL" ] && \
    [ -f "$NXBOOTSTRAP_PM_REAL/control.txt" ] && \
    [ ! -L "$NXBOOTSTRAP_PM_REAL/control.txt" ] || continue
  controlfolder=$NXBOOTSTRAP_PM_REAL
  break
done
unset NXBOOTSTRAP_PM_ROOTS NXBOOTSTRAP_PM_CANDIDATE NXBOOTSTRAP_PM_REAL
[ -n "$controlfolder" ] || controlfolder="/storage/.config/PortMaster"

# Sourced firmware files must be regular (a symlinked control.txt/mod can
# point anywhere), and CFW_NAME reaches a source path so it must never carry
# a separator or shell-hostile byte.
if [ -f "$controlfolder/control.txt" ] && [ ! -L "$controlfolder/control.txt" ]; then
  source "$controlfolder/control.txt"
  nxbootstrap_install_exit_trap
  nxbootstrap_install_early_traps
  nxbootstrap_observe_cfw_name
  case "${CFW_NAME-}" in
    *[!A-Za-z0-9._-]*|'') NXBOOTSTRAP_MOD_NAME='' ;;
    *) NXBOOTSTRAP_MOD_NAME=$CFW_NAME ;;
  esac
  if [ -n "$NXBOOTSTRAP_MOD_NAME" ] && \
     [ -f "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt" ] && \
     [ ! -L "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt" ]; then
    source "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt"
    nxbootstrap_install_exit_trap
    nxbootstrap_install_early_traps
  fi
  command -v get_controls >/dev/null 2>&1 && get_controls
  case "${ANALOGSTICKS:-${ANALOG_STICKS:-}}" in
    0|1|2)
      NXBOOTSTRAP_ANALOG_STICKS_HINT=${ANALOGSTICKS:-${ANALOG_STICKS:-}}
      export NXINPUT_ANALOG_STICKS_HINT="$NXBOOTSTRAP_ANALOG_STICKS_HINT"
      ;;
    *)
      NXBOOTSTRAP_ANALOG_STICKS_HINT=""
      unset NXINPUT_ANALOG_STICKS_HINT
      ;;
  esac
  nxbootstrap_install_exit_trap
  nxbootstrap_install_early_traps
  export NXCOMPAT_PORTMASTER_DIR="$controlfolder"
else
  unset NXCOMPAT_PORTMASTER_DIR
fi

# Two identities (V3-UPDATE-01). The LOGICAL dir is the path the frontend
# actually invoked (/roms/ports/<id>); it is the lexical identity handed to the
# guest -- a real Unity 6 completes its frame loop under the logical root.
# The PHYSICAL dir is `pwd -P` after cd; it is what framework security, inode
# containment and I/O use. `pwd -P` must NEVER silently replace /roms with
# /storage/roms in the guest's argument.
NXBOOTSTRAP_LOGICAL_GAMEDIR="/$directory/ports/offtheroad"
# The port dir a sibling of the ACTUALLY INVOKED launcher (readlink -f "$0"),
# used both as the fallback and to detect a two-tree divergence.
NXBOOTSTRAP_INVOKED_GAMEDIR="$(cd "$(dirname "$(readlink -f "$0")")" 2>/dev/null && pwd)/offtheroad"
NXBOOTSTRAP_GAMEDIR_REASON=frontend-directory
if [ ! -d "$NXBOOTSTRAP_LOGICAL_GAMEDIR" ]; then
  NXBOOTSTRAP_LOGICAL_GAMEDIR="$NXBOOTSTRAP_INVOKED_GAMEDIR"
  NXBOOTSTRAP_GAMEDIR_REASON=invoked-launcher-fallback
elif [ -d "$NXBOOTSTRAP_INVOKED_GAMEDIR" ] && \
     ! [ "$NXBOOTSTRAP_LOGICAL_GAMEDIR" -ef "$NXBOOTSTRAP_INVOKED_GAMEDIR" ]; then
  # /roms and /storage/roms are DISTINCT trees that BOTH hold this port: never
  # run the frontend's copy blindly. Prefer the tree the launcher was actually
  # invoked from (its own sibling), and record the divergence (NXU0007).
  echo "NXU0007: distinct port trees frontend=$NXBOOTSTRAP_LOGICAL_GAMEDIR invoked=$NXBOOTSTRAP_INVOKED_GAMEDIR; preferring the invoked launcher's tree" >&2
  NXBOOTSTRAP_LOGICAL_GAMEDIR="$NXBOOTSTRAP_INVOKED_GAMEDIR"
  NXBOOTSTRAP_GAMEDIR_REASON=invoked-launcher-over-divergent-tree
fi
GAMEDIR="$NXBOOTSTRAP_LOGICAL_GAMEDIR"  # provisional: the ATTEMPTED dir, so an
                                        # early failure records it, not "unresolved"
cd "$GAMEDIR" || exit 1
GAMEDIR=$(pwd -P)                       # physical: framework security and I/O
NXBOOTSTRAP_PHYSICAL_GAMEDIR="$GAMEDIR"

# Record whether this run could put an image on the panel at all.  A launch
# from a remote shell can fail to open a window for reasons that have nothing
# to do with the game, and a black frame collected that way is evidence about
# the harness, not the port.  The frontend starts us with no SSH_* in the
# environment; a remote operator always carries them.
if [ -z "$SSH_CONNECTION" ] && [ -z "$SSH_TTY" ] && [ -z "$SSH_CLIENT" ]; then
  export NXLAUNCH_FRONTEND=1
fi

# Wayland firmwares (ROCKNIX/sway) try to fullscreen the port window by
# app_id derived from the port name; an SDL window without an explicit app id
# never matches and their helper retries into the log forever.  Naming the
# window costs nothing elsewhere and turns that helper into a working
# fullscreen.  Inherited values win (a CFW that sets its own id knows better).
[ -n "${SDL_APP_ID:-}" ] || export SDL_APP_ID="offtheroad"
[ -n "${SDL_VIDEO_WAYLAND_WMCLASS:-}" ] || \
  export SDL_VIDEO_WAYLAND_WMCLASS="offtheroad"

# Two previous generations survive: the run that showed the bug is often the
# one BEFORE the run that collected the log.
[ -s "$GAMEDIR/log.prev.txt" ] && mv -f "$GAMEDIR/log.prev.txt" "$GAMEDIR/log.prev2.txt" 2>/dev/null
[ -s "$GAMEDIR/log.txt" ] && mv -f "$GAMEDIR/log.txt" "$GAMEDIR/log.prev.txt" 2>/dev/null
[ -s "$GAMEDIR/events.jsonl" ] && [ ! -L "$GAMEDIR/events.jsonl" ] && \
  mv -f "$GAMEDIR/events.jsonl" "$GAMEDIR/events.prev.jsonl" 2>/dev/null
if ! exec > "$GAMEDIR/log.txt" 2>&1; then
  printf 'nxbootstrap: cannot open the runtime log\n' >&2
  exit 1
fi
if ! echo "== Off The Road | nxbootstrap 0.6.32 | cfw=${CFW_NAME:-none} =="; then
  exit 1
fi
NXBOOTSTRAP_EARLY_LOG_ACTIVE=0
# Sanitized path receipt (V3-UPDATE-01): both identities and the choice, so a
# silent /roms -> /storage/roms swap is visible in the log, never hidden.
if [ "$NXBOOTSTRAP_LOGICAL_GAMEDIR" = "$NXBOOTSTRAP_PHYSICAL_GAMEDIR" ]; then
  echo "gamedir logical=$NXBOOTSTRAP_LOGICAL_GAMEDIR physical=same selection=$NXBOOTSTRAP_GAMEDIR_REASON"
else
  echo "gamedir logical=$NXBOOTSTRAP_LOGICAL_GAMEDIR physical=$NXBOOTSTRAP_PHYSICAL_GAMEDIR selection=$NXBOOTSTRAP_GAMEDIR_REASON root=symlinked-same-inode"
fi

# Durable latest-boundary record.  Every transition is published by an
# exclusive temporary file and rename before the following phase can begin.
# Runtime adapters receive the same schema/path and remain the authority for
# video-provider and first-frame observations; the launcher never fabricates
# either event or inserts a pipe into the native process flow.
NXBOOTSTRAP_PHASE_SEQUENCE=0
NXBOOTSTRAP_PHASE_FILE="$GAMEDIR/nxphase-result.json"
NXOBS_PHASE_PROTOCOL=nxbootstrap-phase-v1
NXOBS_PHASE_FILE=$NXBOOTSTRAP_PHASE_FILE
NXOBS_EVENT_PROTOCOL=nx-event-v1
NXOBS_EVENT_SINK=stdout
NXOBS_RUN_ID=offtheroad-$$
# V3-OBS-01: one non-reusable run id crosses launcher, NXExtract, adapter,
# loader and game. PID alone repeats across reboots; add wall-clock (only as
# entropy, never authority) and $RANDOM.
NXOBS_RUN_ID="$NXOBS_RUN_ID-$(date +%s 2>/dev/null || printf 0)-$RANDOM"
NXOBS_EVENTS_FILE="$GAMEDIR/events.jsonl"
NXOBS_BOOTSTRAP_VERSION=0.6.32
NXOBS_PHASE_SCHEMA_VERSION=1
export NXOBS_PHASE_PROTOCOL NXOBS_PHASE_FILE NXOBS_EVENT_PROTOCOL \
  NXOBS_EVENT_SINK NXOBS_RUN_ID NXOBS_BOOTSTRAP_VERSION \
  NXOBS_PHASE_SCHEMA_VERSION NXOBS_EVENTS_FILE
nxbootstrap_phase_event() {
  local phase=$1 boundary=$2 source=$3 reason_code=$4 child_status=${5:-}
  local event_status phase_tmp child_json event_details
  case "$phase" in ''|*[!A-Za-z0-9._-]*) return 2 ;; esac
  case "$source" in
    bootstrap|extractor|loader|graphics|audio|input|lifecycle|diagnostic) ;;
    *) return 2 ;;
  esac
  case "$reason_code" in ''|*[!0-9]*) return 2 ;; esac
  [ "$reason_code" -le 9999 ] 2>/dev/null || return 2
  case "$boundary" in
    START) event_status=begin ;;
    OK) event_status=ok ;;
    ERROR) event_status=failed ;;
    OBSERVED) event_status=observed ;;
    EXIT)
      case "$child_status" in ''|*[!0-9]*) return 2 ;; esac
      if [ "$child_status" -eq 0 ]; then event_status=ok; else event_status=failed; fi
      ;;
    *) return 2 ;;
  esac
  case "$child_status" in
    '') child_json=null; event_details='{}' ;;
    *[!0-9]*) return 2 ;;
    *) child_json=$child_status; event_details="{\"child_status\":$child_status}" ;;
  esac
  if [ -L "$NXBOOTSTRAP_PHASE_FILE" ] || [ -d "$NXBOOTSTRAP_PHASE_FILE" ]; then
    echo "ERROR: phase result path is unsafe"
    return 1
  fi
  NXBOOTSTRAP_PHASE_SEQUENCE=$((NXBOOTSTRAP_PHASE_SEQUENCE + 1))
  phase_tmp="$GAMEDIR/.nxphase-result.json.tmp.$$.$NXBOOTSTRAP_PHASE_SEQUENCE.$RANDOM"
  if ! (umask 077; set -C; printf '%s\n' \
    "{\"schema\":\"org.nextos.nxbootstrap.phase-result\",\"schema_version\":1,\"nxbootstrap_version\":\"0.6.32\",\"sequence\":$NXBOOTSTRAP_PHASE_SEQUENCE,\"run_id\":\"$NXOBS_RUN_ID\",\"source\":\"$source\",\"phase\":\"$phase\",\"boundary\":\"$boundary\",\"status\":\"$event_status\",\"reason_code\":$reason_code,\"child_status\":$child_json,\"pid\":$$}" \
    > "$phase_tmp" && mv -f "$phase_tmp" "$NXBOOTSTRAP_PHASE_FILE"); then
    rm -f "$phase_tmp" 2>/dev/null || true
    echo "ERROR: could not publish phase boundary: $phase $boundary"
    return 1
  fi
  if [ "$boundary" = EXIT ]; then
    printf 'PHASE %s EXIT status=%s\n' "$phase" "$child_status"
  else
    printf 'PHASE %s %s\n' "$phase" "$boundary"
  fi
  printf 'NXEVENT {"schema":"nx-event-v1","source":"%s","phase":"%s","status":"%s","reason_code":%s,"details":%s}\n' \
    "$source" "$phase" "$event_status" "$reason_code" "$event_details"
  if [ -n "${NXOBS_EVENTS_FILE:-}" ] && [ ! -L "$NXOBS_EVENTS_FILE" ] && \
     [ ! -d "$NXOBS_EVENTS_FILE" ]; then
    printf '{"schema":"nx-event-v1","schema_version":1,"run_id":"%s","sequence":%s,"source":"%s","component":"nxbootstrap","component_version":"0.6.32","phase":"%s","status":"%s","reason_code":%s,"details":%s}\n' \
      "$NXOBS_RUN_ID" "$NXBOOTSTRAP_PHASE_SEQUENCE" "$source" "$phase" \
      "$event_status" "$reason_code" "$event_details" \
      >> "$NXOBS_EVENTS_FILE" 2>/dev/null || true
  fi
}

# V3-UPDATE-01/NXU####: structured update/generation receipt helper.
nxbootstrap_update_event() {
  local code=$1 detail=$2
  case "$code" in NXU[0-9][0-9][0-9][0-9]) ;; *) return 2 ;; esac
  echo "UPDATE $code: $detail"
  if [ -n "${NXOBS_EVENTS_FILE:-}" ] && [ ! -L "$NXOBS_EVENTS_FILE" ]; then
    printf '{"schema":"nx-event-v1","schema_version":1,"run_id":"%s","source":"bootstrap","component":"nxbootstrap","component_version":"0.6.32","phase":"generation","status":"observed","code":"%s","details":{"note":"%s"}}\n' \
      "$NXOBS_RUN_ID" "$code" "$detail" >> "$NXOBS_EVENTS_FILE" 2>/dev/null || true
  fi
}
# V3-RUNTIME-01/NXR####: structured RUNTIME (single-instance/reaper) event -- a
# DISTINCT family from the NXU update/generation codes. Routing an NXR code
# through nxbootstrap_update_event silently dropped it (the NXU#### case did not
# match, so the helper returned 2 with no log line at all).
nxbootstrap_runtime_event() {
  local code=$1 detail=$2
  case "$code" in NXR[0-9][0-9][0-9][0-9]) ;; *) return 2 ;; esac
  echo "RUNTIME $code: $detail"
  if [ -n "${NXOBS_EVENTS_FILE:-}" ] && [ ! -L "$NXOBS_EVENTS_FILE" ]; then
    printf '{"schema":"nx-event-v1","schema_version":1,"run_id":"%s","source":"bootstrap","component":"nxbootstrap","component_version":"0.6.32","phase":"runtime","status":"observed","code":"%s","details":{"note":"%s"}}\n' \
      "$NXOBS_RUN_ID" "$code" "$detail" >> "$NXOBS_EVENTS_FILE" 2>/dev/null || true
  fi
}
# --- V3-UPDATE-01 / V3-ROLLBACK-01 / V3-CLOCK-01 ------------------------------
# Immutable side-by-side generations under $GAMEDIR/.nxruntime/generations.
# Selection NEVER uses mtime/ctime/filename ordering: only the launcher's own
# baked generation id, the commit markers and the atomic local state. A hybrid
# member-by-member install (old launcher + new runtime, or the reverse) is
# detected by content hash and SELF-HEALED from the chosen complete
# generation; owner data (gamedata, saves, NEXTOSCONTROLLERS.gptk,
# NEXTOSSETTINGS.txt) is never touched. Nothing here deletes a generation.
NXBOOTSTRAP_GENERATION_ID=6e56b833a415a539dfde36cbd4c2832738f6282ca01d83fe8259aec3d4cd1fc9
NXRUNTIME_DIR="$GAMEDIR/.nxruntime"
NXRUNTIME_STATE="$NXRUNTIME_DIR/state.json"
nxbootstrap_state_field() {
  # state.json is one flat JSON line written only by this launcher/nxdoctor.
  sed -n 's/.*"'"$1"'":"\{0,1\}\([A-Za-z0-9_-]*\)"\{0,1\}.*/\1/p' \
    "$NXRUNTIME_STATE" 2>/dev/null | head -n 1
}
nxbootstrap_generation_id_valid() {
  local value=$1
  case "$value" in ''|*[!0-9a-f]*) return 1 ;; esac
  # Read old 128-bit-truncated generations during migration, but every newly
  # generated identity is the complete SHA-256 (64 hex).
  [ "${#value}" -eq 32 ] || [ "${#value}" -eq 64 ]
}
nxbootstrap_state_id_or_null() {
  [ "$1" = null ] || nxbootstrap_generation_id_valid "$1"
}
nxbootstrap_write_state() {
  local active=$1 pending=$2 previous=$3 seq=$4 failures=$5
  local failure_generation=${6:-null} last_health_run_id=${7:-null} state_tmp
  nxbootstrap_state_id_or_null "$active" || return 1
  nxbootstrap_state_id_or_null "$pending" || return 1
  nxbootstrap_state_id_or_null "$previous" || return 1
  nxbootstrap_state_id_or_null "$failure_generation" || return 1
  case "$seq:$failures" in *[!0-9:]*) return 1 ;; esac
  case "$last_health_run_id" in
    null) ;;
    ''|*[!A-Za-z0-9._-]*) return 1 ;;
  esac
  [ "${#last_health_run_id}" -le 192 ] || return 1
  [ -d "$NXRUNTIME_DIR" ] || mkdir -p "$NXRUNTIME_DIR" 2>/dev/null || return 1
  state_tmp="$NXRUNTIME_DIR/.state.json.tmp.$$.$RANDOM"
  if (umask 077; set -C; printf '%s\n' \
    "{\"schema\":\"nxruntime-state-v2\",\"schema_version\":2,\"active\":\"$active\",\"pending\":\"$pending\",\"previous_healthy\":\"$previous\",\"activation_seq\":$seq,\"prehealth_failures\":$failures,\"failure_generation\":\"$failure_generation\",\"last_health_run_id\":\"$last_health_run_id\"}" \
    > "$state_tmp") && mv -f "$state_tmp" "$NXRUNTIME_STATE"; then
    return 0
  fi
  rm -f "$state_tmp" 2>/dev/null || true
  return 1
}
nxbootstrap_generation_complete() {
  # commit marker matches the directory name AND, when sha256sum exists,
  # every listed component hash checks out. Without sha256sum the commit
  # marker plus file presence is the honest maximum this device can prove.
  local generation_root=$1 generation_name commit_value commit_extra
  local component_line component_hash component_path component_source
  local component_count=0 saw_launcher=0 saw_manifest=0 component_actual
  generation_name=${generation_root##*/}
  nxbootstrap_generation_id_valid "$generation_name" || return 1
  [ -d "$generation_root" ] && [ ! -L "$generation_root" ] || return 1
  [ -f "$generation_root/commit" ] && [ ! -L "$generation_root/commit" ] || return 1
  read -r commit_value < "$generation_root/commit" || return 1
  [ "$commit_value" = "$generation_name" ] || return 1
  ! IFS= read -r commit_extra < <(sed -n '2p' "$generation_root/commit") || return 1
  [ -f "$generation_root/manifest.json" ] && \
    [ ! -L "$generation_root/manifest.json" ] || return 1
  [ -f "$generation_root/components.sha256" ] && \
    [ ! -L "$generation_root/components.sha256" ] || return 1
  while IFS= read -r component_line; do
    component_hash=${component_line%%  *}
    component_path=${component_line#*  }
    [ "$component_path" != "$component_line" ] || return 1
    [ "${#component_hash}" -eq 64 ] || return 1
    case "$component_hash" in *[!0-9a-f]*) return 1 ;; esac
    case "$component_path" in
      "launcher/Off The Road.sh") saw_launcher=$((saw_launcher + 1)) ;;
      nxport.json) saw_manifest=$((saw_manifest + 1)) ;;
      *) return 1 ;;
    esac
    component_count=$((component_count + 1))
    component_source="$generation_root/files/$component_path"
    [ -f "$component_source" ] && [ ! -L "$component_source" ] || return 1
    if command -v sha256sum >/dev/null 2>&1; then
      component_actual=$(sha256sum "$component_source" 2>/dev/null) || return 1
      component_actual=${component_actual%% *}
      [ "$component_actual" = "$component_hash" ] || return 1
    fi
  done < "$generation_root/components.sha256"
  [ "$component_count" -eq 2 ] && [ "$saw_launcher" -eq 1 ] && \
    [ "$saw_manifest" -eq 1 ] || return 1
  return 0
}
NXBOOTSTRAP_SELECTED_GENERATION=""
if [ -d "$NXRUNTIME_DIR/generations" ]; then
  nxbootstrap_state_active=$(nxbootstrap_state_field active)
  nxbootstrap_state_pending=$(nxbootstrap_state_field pending)
  nxbootstrap_state_previous=$(nxbootstrap_state_field previous_healthy)
  nxbootstrap_state_seq=$(nxbootstrap_state_field activation_seq)
  nxbootstrap_state_failures=$(nxbootstrap_state_field prehealth_failures)
  nxbootstrap_state_failure_generation=$(nxbootstrap_state_field failure_generation)
  nxbootstrap_state_last_health_run=$(nxbootstrap_state_field last_health_run_id)
  case "$nxbootstrap_state_seq" in ''|*[!0-9]*) nxbootstrap_state_seq=0 ;; esac
  case "$nxbootstrap_state_failures" in ''|*[!0-9]*) nxbootstrap_state_failures=0 ;; esac
  nxbootstrap_generation_id_valid "$nxbootstrap_state_active" || nxbootstrap_state_active=null
  nxbootstrap_generation_id_valid "$nxbootstrap_state_pending" || nxbootstrap_state_pending=null
  nxbootstrap_generation_id_valid "$nxbootstrap_state_previous" || nxbootstrap_state_previous=null
  nxbootstrap_generation_id_valid "$nxbootstrap_state_failure_generation" || nxbootstrap_state_failure_generation=null
  # Crash-loop guard is tied to one PENDING generation. A stable active
  # generation is never demoted because an unrelated run happened to fail.
  if [ "$nxbootstrap_state_failures" -ge 3 ] && \
     [ "$nxbootstrap_state_pending" != null ] && \
     [ "$nxbootstrap_state_failure_generation" = "$nxbootstrap_state_pending" ] && \
     [ -n "$nxbootstrap_state_previous" ] && \
     [ "$nxbootstrap_state_previous" != "null" ] && \
     nxbootstrap_generation_complete "$NXRUNTIME_DIR/generations/$nxbootstrap_state_previous"; then
    NXBOOTSTRAP_SELECTED_GENERATION=$nxbootstrap_state_previous
    nxbootstrap_update_event NXU0004 "crash-loop: previous healthy generation $nxbootstrap_state_previous selected"
    nxbootstrap_write_state "$nxbootstrap_state_previous" "null" \
      "$nxbootstrap_state_previous" "$nxbootstrap_state_seq" 0 "null" \
      "${nxbootstrap_state_last_health_run:-null}" || true
    nxbootstrap_state_active=$nxbootstrap_state_previous
    nxbootstrap_state_pending=null
    nxbootstrap_state_failures=0
    nxbootstrap_state_failure_generation=null
  elif [ -n "$NXBOOTSTRAP_GENERATION_ID" ] && \
     nxbootstrap_generation_complete "$NXRUNTIME_DIR/generations/$NXBOOTSTRAP_GENERATION_ID"; then
    NXBOOTSTRAP_SELECTED_GENERATION=$NXBOOTSTRAP_GENERATION_ID
  elif [ "$nxbootstrap_state_pending" != null ] && \
       nxbootstrap_generation_complete "$NXRUNTIME_DIR/generations/$nxbootstrap_state_pending"; then
    NXBOOTSTRAP_SELECTED_GENERATION=$nxbootstrap_state_pending
    nxbootstrap_update_event NXU0008 "pending generation $nxbootstrap_state_pending selected for health trial"
  elif [ -n "$nxbootstrap_state_active" ] && \
       [ "$nxbootstrap_state_active" != "null" ] && \
       nxbootstrap_generation_complete "$NXRUNTIME_DIR/generations/$nxbootstrap_state_active"; then
    NXBOOTSTRAP_SELECTED_GENERATION=$nxbootstrap_state_active
    nxbootstrap_update_event NXU0002 "own generation $NXBOOTSTRAP_GENERATION_ID incomplete; running last good $nxbootstrap_state_active"
  else
    for nxbootstrap_candidate in "$NXRUNTIME_DIR/generations"/*/; do
      [ -d "$nxbootstrap_candidate" ] || continue
      nxbootstrap_candidate=${nxbootstrap_candidate%/}
      if nxbootstrap_generation_complete "$nxbootstrap_candidate"; then
        NXBOOTSTRAP_SELECTED_GENERATION=${nxbootstrap_candidate##*/}
        nxbootstrap_update_event NXU0002 "no state; complete generation ${nxbootstrap_candidate##*/} selected"
        break
      fi
      nxbootstrap_update_event NXU0002 "generation ${nxbootstrap_candidate##*/} is truncated or stale; ignored (not deleted)"
    done
  fi
  if [ -n "$NXBOOTSTRAP_SELECTED_GENERATION" ]; then
    nxbootstrap_generation_root="$NXRUNTIME_DIR/generations/$NXBOOTSTRAP_SELECTED_GENERATION"
    if [ "$NXBOOTSTRAP_SELECTED_GENERATION" != "$NXBOOTSTRAP_GENERATION_ID" ]; then
      nxbootstrap_update_event NXU0001 "mixed installation: launcher carries $NXBOOTSTRAP_GENERATION_ID, runtime generation is $NXBOOTSTRAP_SELECTED_GENERATION"
    fi
    # Self-heal divergent root components from the selected generation.
    if command -v sha256sum >/dev/null 2>&1; then
      while IFS= read -r nxbootstrap_component_line; do
        nxbootstrap_expected=${nxbootstrap_component_line%%  *}
        nxbootstrap_relpath=${nxbootstrap_component_line#*  }
        case "$nxbootstrap_relpath" in
          gamedata/*|saves/*|NEXTOSCONTROLLERS.gptk|NEXTOSSETTINGS.txt) continue ;;
        esac
        if [ "${nxbootstrap_relpath#launcher/}" != "$nxbootstrap_relpath" ]; then
          nxbootstrap_root_target="$NXBOOTSTRAP_LAUNCHER_DIR/${nxbootstrap_relpath#launcher/}"
        else
          nxbootstrap_root_target="$GAMEDIR/$nxbootstrap_relpath"
        fi
        # The source component must be a real file in the generation, never a
        # symlink (a symlinked generation member could point outside the port).
        nxbootstrap_heal_src="$nxbootstrap_generation_root/files/$nxbootstrap_relpath"
        [ -f "$nxbootstrap_heal_src" ] && [ ! -L "$nxbootstrap_heal_src" ] || continue
        # Never read the hash THROUGH a symlinked target: a symlink is itself a
        # divergence to heal (replaced by the real file), not followed.
        if [ -L "$nxbootstrap_root_target" ]; then
          nxbootstrap_actual="symlink"
        else
          nxbootstrap_actual=$(sha256sum "$nxbootstrap_root_target" 2>/dev/null)
          nxbootstrap_actual=${nxbootstrap_actual%% *}
        fi
        if [ "$nxbootstrap_actual" != "$nxbootstrap_expected" ]; then
          nxbootstrap_update_event NXU0003 "healing $nxbootstrap_relpath expected=$nxbootstrap_expected observed=${nxbootstrap_actual:-absent}"
          nxbootstrap_heal_tmp="$nxbootstrap_root_target.nxheal.$$"
          rm -f "$nxbootstrap_heal_tmp" 2>/dev/null || true
          # Atomic: write the temp, VERIFY its hash equals the expected content,
          # and only THEN rename over the target. A failed/short cat can never
          # leave a truncated file installed (the previous cat && chmod || chmod
          # chain would mv a partial temp when cat failed).
          if cat "$nxbootstrap_heal_src" > "$nxbootstrap_heal_tmp" 2>/dev/null; then
            nxbootstrap_heal_check=$(sha256sum "$nxbootstrap_heal_tmp" 2>/dev/null)
            nxbootstrap_heal_check=${nxbootstrap_heal_check%% *}
            if [ "$nxbootstrap_heal_check" = "$nxbootstrap_expected" ]; then
              case "$nxbootstrap_relpath" in
                launcher/*) nxbootstrap_heal_mode=755 ;;
                nxport.json) nxbootstrap_heal_mode=644 ;;
              esac
              chmod "$nxbootstrap_heal_mode" "$nxbootstrap_heal_tmp" \
                2>/dev/null || true
              mv -f "$nxbootstrap_heal_tmp" "$nxbootstrap_root_target" 2>/dev/null || \
                rm -f "$nxbootstrap_heal_tmp" 2>/dev/null || true
            else
              rm -f "$nxbootstrap_heal_tmp" 2>/dev/null || true
            fi
          else
            rm -f "$nxbootstrap_heal_tmp" 2>/dev/null || true
          fi
        fi
      done < "$nxbootstrap_generation_root/components.sha256"
    fi
    # A new generation stays PENDING. It does not replace active until an
    # exact, run-bound health receipt is validated after the child exits.
    if [ "$nxbootstrap_state_active" != "$NXBOOTSTRAP_SELECTED_GENERATION" ]; then
      if [ "$nxbootstrap_state_pending" != "$NXBOOTSTRAP_SELECTED_GENERATION" ]; then
        nxbootstrap_state_previous=$nxbootstrap_state_active
        [ "$nxbootstrap_state_previous" != null ] || \
          nxbootstrap_state_previous=${nxbootstrap_state_previous:-null}
        nxbootstrap_state_seq=$((nxbootstrap_state_seq + 1))
        nxbootstrap_state_failures=0
      fi
      nxbootstrap_state_pending=$NXBOOTSTRAP_SELECTED_GENERATION
      nxbootstrap_state_failure_generation=$NXBOOTSTRAP_SELECTED_GENERATION
      nxbootstrap_write_state "${nxbootstrap_state_active:-null}" \
        "$nxbootstrap_state_pending" "${nxbootstrap_state_previous:-null}" \
        "$nxbootstrap_state_seq" "$nxbootstrap_state_failures" \
        "$nxbootstrap_state_failure_generation" \
        "${nxbootstrap_state_last_health_run:-null}" || true
    fi
  elif [ -n "$(ls -A "$NXRUNTIME_DIR/generations" 2>/dev/null)" ]; then
    nxbootstrap_update_event NXU0001 "no complete generation found; continuing with the installed root files (nothing deleted)"
  fi
fi
# ------------------------------------------------------------------------------

nxbootstrap_validate_nxextract_result() {
  python3 -B - "$1" "$2" <<'PY'
import json
import os
import re
import stat
import sys

sys.tracebacklimit = 0
path, process_status_text = sys.argv[1:]
process_status = int(process_status_text)
# Members born WITH schema_version 1 are required. Members added LATER in the
# same schema_version (ui, and any future addition) are validated only when
# present -- BOTH directions of a partially updated install keep working:
# old launcher + new engine (extra member ignored there) and new launcher +
# old engine (missing member tolerated here).
top_keys = {
    "schema", "schema_version", "nxextract_version", "outcome", "code",
    "final_phase", "recipe", "package_id", "abi", "container",
    "validated", "logs", "duration_ms", "completed_unix", "error",
}
phase_ids = (
    "preparing", "scanning", "validating-packages", "selecting",
    "extracting", "processing", "validating-data", "installing", "ready",
)
sha256_re = re.compile(r"^[0-9a-f]{64}$")
safe_id_re = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")

def reject(message):
    raise ValueError(message)

def pairs(items):
    result = {}
    for key, value in items:
        if key in result:
            reject("duplicate JSON member")
        result[key] = value
    return result

def finite_constant(_value):
    reject("non-finite JSON number")

def exact_object(value, keys, label):
    if not isinstance(value, dict) or set(value) != set(keys):
        reject("invalid " + label + " object")


def require_members(value, keys, label):
    # 0.6.26: FORWARD-COMPATIBLE. Every known member must be present and is
    # validated below, but EXTRA members added by a newer engine are ignored
    # instead of rejected -- adding a field is a compatible change. The real
    # compatibility contract is schema + schema_version, checked right after.
    if not isinstance(value, dict) or not set(keys) <= set(value):
        reject("invalid " + label + " object")

def integer(value, label):
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        reject("invalid " + label)

def string(value, minimum, maximum, label):
    if not isinstance(value, str) or not minimum <= len(value) <= maximum:
        reject("invalid " + label)
    if any(ord(char) < 32 for char in value):
        reject("control byte in " + label)

def relative_path(value, label):
    string(value, 1, 512, label)
    if value.startswith("/") or "\\" in value or ".." in value.split("/"):
        reject("invalid " + label)

flags = (os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) |
         getattr(os, "O_NOFOLLOW", 0))
fd = os.open(path, flags)
try:
    opened = os.fstat(fd)
    linked = os.lstat(path)
    if (not stat.S_ISREG(opened.st_mode) or opened.st_nlink != 1 or
            (opened.st_dev, opened.st_ino) != (linked.st_dev, linked.st_ino)):
        reject("unsafe result identity")
    chunks = []
    total = 0
    while True:
        block = os.read(fd, 65536)
        if not block:
            break
        total += len(block)
        if total > 1048576:
            reject("result exceeds size limit")
        chunks.append(block)
finally:
    os.close(fd)

document = json.loads(
    b"".join(chunks).decode("utf-8", "strict"),
    object_pairs_hook=pairs,
    parse_constant=finite_constant,
)
require_members(document, top_keys, "terminal result")
# The compatibility contract is the schema id + schema_version ONLY. A newer
# engine (any nxextract_version) that keeps schema_version 1 stays readable by
# this launcher -- so a partially-updated install (new engine under an older
# launcher .sh) no longer dies with "unknown terminal result schema". A real
# breaking change would bump schema_version, which this gate still rejects.
if (document["schema"] != "org.nextos.nxextract.terminal-result" or
        isinstance(document["schema_version"], bool) or
        document["schema_version"] != 1 or
        not isinstance(document["nxextract_version"], str) or
        re.fullmatch(r"[0-9]{1,4}\.[0-9]{1,4}\.[0-9]{1,4}",
                     document["nxextract_version"]) is None):
    reject("unknown terminal result schema")
if document["outcome"] not in ("success", "error"):
    reject("invalid terminal outcome")
if (process_status == 0) != (document["outcome"] == "success"):
    reject("process status and terminal outcome disagree")
if (not isinstance(document["code"], str) or
        not re.fullmatch(r"^NXE[0-9]{4}$", document["code"])):
    reject("invalid terminal code")

phase = document["final_phase"]
exact_object(phase, ("index", "id", "label"), "final phase")
integer(phase["index"], "phase index")
if phase["index"] > 8 or phase["id"] != phase_ids[phase["index"]]:
    reject("invalid final phase")
string(phase["label"], 1, 64, "phase label")

recipe = document["recipe"]
exact_object(recipe, ("id", "version", "digest"), "recipe")
if (not isinstance(recipe["id"], str) or
        not safe_id_re.fullmatch(recipe["id"])):
    reject("invalid recipe id")
string(recipe["version"], 1, 128, "recipe version")
if (not isinstance(recipe["digest"], str) or
        not sha256_re.fullmatch(recipe["digest"])):
    reject("invalid recipe digest")

if document["package_id"] is not None:
    string(document["package_id"], 1, 255, "package id")
abi = document["abi"]
if (abi is not None and
        (not isinstance(abi, str) or
         not re.fullmatch(r"^[A-Za-z0-9._-]{1,64}$", abi))):
    reject("invalid ABI")
container = document["container"]
exact_object(container, ("kind", "identity"), "container")
if container["kind"] not in (
        "apk-set", "bundle", "companion", "existing", None):
    reject("invalid container kind")
identity = container["identity"]
if (identity is not None and
        (not isinstance(identity, str) or not sha256_re.fullmatch(identity))):
    reject("invalid container identity")

validated = document["validated"]
exact_object(validated, ("items", "bytes", "critical_payloads"), "validated")
integer(validated["items"], "validated item count")
integer(validated["bytes"], "validated byte count")
critical = validated["critical_payloads"]
if not isinstance(critical, list) or len(critical) > 256:
    reject("invalid critical payload list")
for item in critical:
    exact_object(item, ("id", "items", "bytes"), "critical payload")
    if (not isinstance(item["id"], str) or
            not safe_id_re.fullmatch(item["id"])):
        reject("invalid critical payload id")
    integer(item["items"], "critical payload item count")
    integer(item["bytes"], "critical payload byte count")

logs = document["logs"]
exact_object(logs, ("summary", "detail"), "logs")
relative_path(logs["summary"], "summary log")
relative_path(logs["detail"], "detail log")
integer(document["duration_ms"], "duration")
integer(document["completed_unix"], "completion time")

if "ui" in document:
    ui = document["ui"]
    exact_object(ui, ("mode", "renderer", "fallback_reason"), "ui")
    if ui["mode"] not in ("visible", "headless-fallback", "disabled"):
        reject("invalid ui mode")
    if ui["renderer"] is not None:
        string(ui["renderer"], 1, 32, "ui renderer")
    if ui["fallback_reason"] is not None:
        string(ui["fallback_reason"], 1, 512, "ui fallback reason")
    if (ui["mode"] == "headless-fallback") != (
            ui["fallback_reason"] is not None):
        reject("ui mode and fallback reason disagree")

error = document["error"]
if document["outcome"] == "success":
    if error is not None:
        reject("success result contains an error")
else:
    exact_object(error, ("class", "message"), "error")
    if (not isinstance(error["class"], str) or
            not re.fullmatch(r"^[A-Za-z][A-Za-z0-9_]{0,127}$",
                             error["class"])):
        reject("invalid error class")
    string(error["message"], 1, 512, "error message")

print(json.dumps(document, ensure_ascii=True, sort_keys=True,
                 separators=(",", ":")))
PY
}

nxbootstrap_phase_event preflight START bootstrap 6190 || {
  nxbootstrap_finish
  exit 1
}

# The executable is itself required and is touched before the owner-data phase.
NXBOOTSTRAP_EXECUTABLE=$(readlink -f "$GAMEDIR/offtheroad" 2>/dev/null) || NXBOOTSTRAP_EXECUTABLE=""
case "$NXBOOTSTRAP_EXECUTABLE" in
  "$GAMEDIR"/*) ;;
  *) NXBOOTSTRAP_EXECUTABLE="" ;;
esac
if [ -z "$NXBOOTSTRAP_EXECUTABLE" ] || [ ! -f "$NXBOOTSTRAP_EXECUTABLE" ] || \
   [ ! -s "$NXBOOTSTRAP_EXECUTABLE" ] || [ -L "$GAMEDIR/offtheroad" ]; then
  echo "ERROR: executable is missing or unsafe: offtheroad"
  nxbootstrap_finish
  exit 1
fi

# Dynamic-loader (PT_INTERP) preflight: an ELF whose interpreter is absent
# exec()s with ENOENT, which the shell reports as "No such file or directory"
# for the binary and a bare status 127 -- a black screen that looks like a
# broken port but is a missing device runtime. Textbook case: a 32-bit ARMHF
# port on a 64-bit-only CFW with no 32-bit ARM runtime (spruce/Miyoo Flip:
# /lib/ld-linux-armhf.so.3 absent). `grep -a` reads the early .interp; a static
# or unreadable ELF yields nothing and skips the check (never a false block).
# Prefix that runs the game THROUGH an explicit loader (empty for every normal
# port -- the run line then executes "$BIN" byte-identically). Only set below,
# for the spruce/Miyoo-Flip case where the 32-bit loader lives off the default
# path.
NXBOOTSTRAP_INTERP_PREFIX=""
NXBOOTSTRAP_INTERP=$(LC_ALL=C grep -a -o -m1 -E '/lib(32|64)?/ld-[A-Za-z0-9._-]*\.so[A-Za-z0-9._-]*' "$NXBOOTSTRAP_EXECUTABLE" 2>/dev/null | head -n1)
if [ -n "$NXBOOTSTRAP_INTERP" ] && [ ! -e "$NXBOOTSTRAP_INTERP" ]; then
  # The interpreter is absent at the exact path baked into the ELF. Before
  # giving up, look for the SAME loader elsewhere: some CFWs mount their 32-bit
  # runtime off the default path -- spruceOS/Miyoo Flip assembles a 32-bit chroot
  # at boot and copies ld-linux-armhf.so.3 under /usr/lib and /usr/lib32. If we
  # find it, run the game THROUGH that loader with an explicit --library-path
  # (additive: this branch is only reached when the game would otherwise abort).
  NXBOOTSTRAP_INTERP_BASE=$(basename "$NXBOOTSTRAP_INTERP")
  NXBOOTSTRAP_INTERP_ALT=""
  for cand in \
    "/usr/lib/$NXBOOTSTRAP_INTERP_BASE" \
    "/usr/lib32/$NXBOOTSTRAP_INTERP_BASE" \
    "/lib32/$NXBOOTSTRAP_INTERP_BASE" \
    "/mnt/SDCARD/spruce/flip/$NXBOOTSTRAP_INTERP_BASE" \
    "/mnt/SDCARD/spruce/flip/muOS/usr/lib/$NXBOOTSTRAP_INTERP_BASE" \
    "/mnt/SDCARD/Persistent/.32bit_chroot/usr/lib/$NXBOOTSTRAP_INTERP_BASE" \
    "/mnt/SDCARD/Persistent/.32bit_chroot/lib/$NXBOOTSTRAP_INTERP_BASE"; do
    [ -e "$cand" ] && { NXBOOTSTRAP_INTERP_ALT="$cand"; break; }
  done
  if [ -n "$NXBOOTSTRAP_INTERP_ALT" ]; then
    # Diretorios confirmados nas IMAGENS oficiais (spruce v4.3.4): o muOS
    # reduzido tem SDL2/EGL/GLES ARMHF em usr/lib (nao so lib32) e o chroot
    # 32-bit monta em /mnt/SDCARD/Persistent/.32bit_chroot.
    NXBOOTSTRAP_INTERP_LIBS="$GAMEDIR:$GAMEDIR/lib:/usr/lib32:/lib32:/mnt/SDCARD/spruce/flip/muOS/usr/lib:/mnt/SDCARD/spruce/flip/muOS/lib:/mnt/SDCARD/spruce/flip/muOS/lib32:/mnt/SDCARD/spruce/flip/muOS/usr/lib32:/mnt/SDCARD/Persistent/.32bit_chroot/usr/lib:/mnt/SDCARD/Persistent/.32bit_chroot/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    NXBOOTSTRAP_INTERP_PREFIX="$NXBOOTSTRAP_INTERP_ALT --library-path $NXBOOTSTRAP_INTERP_LIBS"
    echo "NOTE: interpreter $NXBOOTSTRAP_INTERP is absent at its default path, but $NXBOOTSTRAP_INTERP_ALT exists; launching offtheroad through it."
  else
    echo "ERROR: offtheroad cannot run here: dynamic loader $NXBOOTSTRAP_INTERP is missing."
    case "$NXBOOTSTRAP_INTERP" in
      *armhf*|*ld-linux.so.3) echo "  32-bit ARM (ARMHF) port, but this CFW has no 32-bit ARM runtime on any known path; use a CFW with 32-bit multiarch (Knulli/ROCKNIX), fix the 32-bit mount (spruce/Miyoo Flip), or use an AArch64 build." ;;
      *aarch64*|*ld-linux-aarch64*) echo "  64-bit ARM (AArch64) port, but this device has no 64-bit ARM runtime." ;;
      *) echo "  this CFW does not provide the runtime this port was built for." ;;
    esac
    nxbootstrap_phase_event preflight ERROR bootstrap 6198 || true
    nxbootstrap_finish
    exit 1
  fi
fi

# Exec bits do not survive zip/FAT/Windows extraction.
$ESUDO chmod +x "$NXBOOTSTRAP_EXECUTABLE" "$GAMEDIR/nxextract-ui" \
  "$GAMEDIR/nxsplash-nextos" "$GAMEDIR"/*.sh 2>/dev/null || true
$ESUDO chmod 666 "$CUR_TTY" /dev/uinput 2>/dev/null || true

# Keep the text console dark across the KMSDRM transition: a slow-loading
# engine (Unity/IL2CPP) would otherwise leave the tty visible -- PortMaster
# get_controls output and boot text -- until its GL window covers the screen,
# and the frontend hand-off already resets it (\033c) on exit. Hide the cursor
# and clear the screen; harmless on fbdev where nothing overlaps.
[ -n "$CUR_TTY" ] && [ -c "$CUR_TTY" ] && \
  printf '\033[?25l\033[2J\033[H' > "$CUR_TTY" 2>/dev/null || true

# One stable lock per port ID, outside the ROM. Replacing the ELF cannot create
# a new lock inode and allow a second game to fight for fb0/audio/input.
# V3-RUNTIME-01: enumerate stale processes whose executable lives under this
# port, including a replaced binary shown as "... (deleted)". A live process
# of the SAME generation means the game is already open: refuse a second
# instance with a readable message. An old/stale one is terminated in a
# controlled way and must be gone before we continue; two instances fighting
# for GPU/framebuffer/audio can freeze the device.
nxbootstrap_stale_sweep() {
  local proc_entry proc_pid proc_exe proc_generation waited
  for proc_entry in /proc/[0-9]*; do
    proc_pid=${proc_entry#/proc/}
    [ "$proc_pid" != "$$" ] || continue
    proc_exe=$(readlink "$proc_entry/exe" 2>/dev/null) || continue
    case "$proc_exe" in
      "$GAMEDIR"/*|"$GAMEDIR"/*" (deleted)") ;;
      *) continue ;;
    esac
    # The stable lock is acquired BEFORE this sweep. A conforming live child
    # therefore prevents us from reaching here at all. This environment check
    # protects an orphan whose runtime closed the inherited lock descriptor:
    # the same generation is a live instance, never "stale" and never killed.
    proc_generation=$(tr '\000' '\n' < "$proc_entry/environ" 2>/dev/null |
      sed -n 's/^NXBOOTSTRAP_HEALTH_GENERATION=//p' | head -n 1)
    if [ -n "$proc_generation" ] && \
       [ "$proc_generation" = "${NXBOOTSTRAP_SELECTED_GENERATION:-none}" ]; then
      nxbootstrap_runtime_event NXR0003 "same generation is already alive pid=$proc_pid; not terminating it and not starting a second instance"
      echo "ERROR NXR0003: the same generation is already running (pid $proc_pid); not starting a second instance"
      nxbootstrap_finish
      exit 1
    fi
    nxbootstrap_runtime_event NXR0001 "stale process pid=$proc_pid exe=${proc_exe##*/}"
    builtin kill -TERM "$proc_pid" 2>/dev/null || true
    waited=0
    while [ -d "$proc_entry" ] && [ "$waited" -lt 5 ]; do
      sleep 1
      waited=$((waited + 1))
    done
    if [ -d "$proc_entry" ]; then
      builtin kill -KILL "$proc_pid" 2>/dev/null || true
      sleep 1
    fi
    if [ -d "$proc_entry" ]; then
      nxbootstrap_runtime_event NXR0002 "a previous instance (pid $proc_pid) is still alive and could not be terminated; not starting a second instance"
      echo "ERROR NXR0002: a previous instance (pid $proc_pid) is still alive and could not be terminated; not starting a second instance"
      nxbootstrap_finish
      exit 1
    fi
  done
}

NXBOOTSTRAP_LOCK_ROOT=${XDG_RUNTIME_DIR:-}
if [ "${NXBOOTSTRAP_LOCK_ROOT#/}" = "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -d "$NXBOOTSTRAP_LOCK_ROOT" ] || [ -L "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_ROOT" ] || [ ! -w "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -x "$NXBOOTSTRAP_LOCK_ROOT" ]; then
  NXBOOTSTRAP_LOCK_ROOT=/tmp
fi
if [ ! -d "$NXBOOTSTRAP_LOCK_ROOT" ] || [ -L "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -w "$NXBOOTSTRAP_LOCK_ROOT" ] || [ ! -x "$NXBOOTSTRAP_LOCK_ROOT" ]; then
  echo "ERROR: no safe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
fi
NXBOOTSTRAP_LOCK_ROOT=$(cd "$NXBOOTSTRAP_LOCK_ROOT" 2>/dev/null && pwd -P) || {
  echo "ERROR: no safe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
}
case "$NXBOOTSTRAP_LOCK_ROOT" in
  "$GAMEDIR"|"$GAMEDIR"/*)
    echo "ERROR: instance lock directory must be outside the game"
    nxbootstrap_finish
    exit 1
    ;;
esac
NXBOOTSTRAP_LOCK_DIR="$NXBOOTSTRAP_LOCK_ROOT/.nxbootstrap-${UID:-$(id -u)}"
if [ ! -e "$NXBOOTSTRAP_LOCK_DIR" ] && [ ! -L "$NXBOOTSTRAP_LOCK_DIR" ]; then
  (umask 077; mkdir "$NXBOOTSTRAP_LOCK_DIR") 2>/dev/null || true
fi
if [ ! -d "$NXBOOTSTRAP_LOCK_DIR" ] || [ -L "$NXBOOTSTRAP_LOCK_DIR" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_DIR" ] || [ ! -w "$NXBOOTSTRAP_LOCK_DIR" ] || \
   [ ! -x "$NXBOOTSTRAP_LOCK_DIR" ] || \
   ! chmod 0700 "$NXBOOTSTRAP_LOCK_DIR" 2>/dev/null; then
  echo "ERROR: unsafe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
fi
NXBOOTSTRAP_LOCK_FILE="$NXBOOTSTRAP_LOCK_DIR/nxport-offtheroad.flock"
if [ -e "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ]; then
  if [ ! -f "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ] || \
     [ ! -O "$NXBOOTSTRAP_LOCK_FILE" ]; then
    echo "ERROR: unsafe instance lock file"
    nxbootstrap_finish
    exit 1
  fi
fi
NXBOOTSTRAP_OLD_UMASK=$(umask)
umask 077
{ exec 9>&-; } 2>/dev/null || true
if ! { exec 9>>"$NXBOOTSTRAP_LOCK_FILE"; } 2>/dev/null; then
  umask "$NXBOOTSTRAP_OLD_UMASK"
  echo "ERROR: cannot open the instance lock"
  nxbootstrap_finish
  exit 1
fi
umask "$NXBOOTSTRAP_OLD_UMASK"
# POSIX/BusyBox/Toybox ls supplies nlink; Bash -ef proves the opened inode.
# Never depend on external stat: some supported muOS images omit it.
NXBOOTSTRAP_LOCK_META=()
IFS=' ' read -r -a NXBOOTSTRAP_LOCK_META \
  <<< "$(LC_ALL=C command ls -Lldn /proc/self/fd/9 2>/dev/null)"
NXBOOTSTRAP_LOCK_LINKS=${NXBOOTSTRAP_LOCK_META[1]:-}
if [ ! -f "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_FILE" ] || [ "$NXBOOTSTRAP_LOCK_LINKS" != 1 ] || \
   ! [ "$NXBOOTSTRAP_LOCK_FILE" -ef /proc/self/fd/9 ]; then
  { exec 9>&-; } 2>/dev/null || true
  echo "ERROR: instance lock identity is unsafe"
  nxbootstrap_finish
  exit 1
fi
unset NXBOOTSTRAP_LOCK_META NXBOOTSTRAP_LOCK_LINKS
# Some BusyBox firmwares ship no flock applet: there the command exits 127 and
# the old message blamed a phantom "other instance" forever.  Distinguish the
# two worlds; without flock, fall back to an owner-stamped mkdir lock (the
# retired 0.5.1 library's proven recipe): stale owner (PID gone) is reclaimed,
# a live owner refuses the double launch.
if command -v flock >/dev/null 2>&1; then
  if ! flock -n 9; then
    echo "another instance holds the lock; not double-launching"
    nxbootstrap_finish
    exit 1
  fi
else
  NXBOOTSTRAP_FALLBACK_LOCK_DIR="$NXBOOTSTRAP_LOCK_FILE.d"
  if mkdir "$NXBOOTSTRAP_FALLBACK_LOCK_DIR" 2>/dev/null; then
    printf '%s\n' "$$" > "$NXBOOTSTRAP_FALLBACK_LOCK_DIR/owner" 2>/dev/null || true
  else
    NXBOOTSTRAP_FALLBACK_LOCK_OWNER=$(LC_ALL=C head -n 1 \
      "$NXBOOTSTRAP_FALLBACK_LOCK_DIR/owner" 2>/dev/null | tr -cd '0-9')
    if [ -n "$NXBOOTSTRAP_FALLBACK_LOCK_OWNER" ] && \
       [ -d "/proc/$NXBOOTSTRAP_FALLBACK_LOCK_OWNER" ]; then
      echo "another instance holds the lock; not double-launching (no flock on this firmware)"
      nxbootstrap_finish
      exit 1
    fi
    echo "stale fallback lock reclaimed (owner ${NXBOOTSTRAP_FALLBACK_LOCK_OWNER:-unknown} is gone)"
    rm -rf "$NXBOOTSTRAP_FALLBACK_LOCK_DIR" 2>/dev/null || true
    if ! mkdir "$NXBOOTSTRAP_FALLBACK_LOCK_DIR" 2>/dev/null; then
      echo "ERROR: cannot take the fallback instance lock"
      nxbootstrap_finish
      exit 1
    fi
    printf '%s\n' "$$" > "$NXBOOTSTRAP_FALLBACK_LOCK_DIR/owner" 2>/dev/null || true
  fi
  # Liberado em nxbootstrap_on_exit (o trap EXIT ja' instalado); nunca
  # instalar outro trap EXIT aqui -- ele SUBSTITUIRIA o do launcher.
fi
# Only after the stable per-port lock is ours may an unprotected process be
# classified as an old/stale generation. Previously the sweep ran first and
# killed a healthy current game before `flock -n` could refuse the duplicate.
nxbootstrap_stale_sweep
# Health proof lives beside the validated process lock, never on FAT/exFAT or
# inside the game tree. The child must publish the exact versioned JSON with an
# exclusive temp + rename; a log line, PID lifetime or exit status is not
# authority. The unique run_id makes a receipt non-reusable across launches.
NXBOOTSTRAP_HEALTH_FILE="$NXBOOTSTRAP_LOCK_DIR/health-offtheroad-$NXOBS_RUN_ID.json"
if [ -e "$NXBOOTSTRAP_HEALTH_FILE" ] || [ -L "$NXBOOTSTRAP_HEALTH_FILE" ]; then
  echo "ERROR: health receipt path unexpectedly exists"
  nxbootstrap_finish
  exit 1
fi
NXBOOTSTRAP_HEALTH_SCHEMA=org.nextos.nxruntime.health
NXBOOTSTRAP_HEALTH_SCHEMA_VERSION=1
NXBOOTSTRAP_HEALTH_RUN_ID=$NXOBS_RUN_ID
NXBOOTSTRAP_HEALTH_GENERATION=${NXBOOTSTRAP_SELECTED_GENERATION:-none}
NXBOOTSTRAP_HEALTH_PORT_ID=offtheroad
export NXBOOTSTRAP_HEALTH_FILE NXBOOTSTRAP_HEALTH_SCHEMA \
  NXBOOTSTRAP_HEALTH_SCHEMA_VERSION NXBOOTSTRAP_HEALTH_RUN_ID \
  NXBOOTSTRAP_HEALTH_GENERATION NXBOOTSTRAP_HEALTH_PORT_ID
BIN="$GAMEDIR/offtheroad"
# 0.6.24: fonte CANONICA de auto-localizacao do guest. Rodando atraves do
# ld-linux explicito (CFW 64-bit-only com runtime ARMHF fora do caminho), o
# /proc/self/exe do jogo aponta pro LD.SO — loaders que se localizavam por ele
# perdiam a propria pasta (caso de campo: gamedir virou a pasta do loader e o
# preflight recusou). NXBOOTSTRAP_EXE e sempre o caminho REAL do executavel.
export NXBOOTSTRAP_EXE="$BIN"

if command -v pm_platform_helper >/dev/null 2>&1; then
  if pm_platform_helper "$BIN"; then
    echo "pm_platform_helper completed before game launch"
  else
    NXBOOTSTRAP_PLATFORM_STATUS=$?
    echo "WARNING: pm_platform_helper returned status $NXBOOTSTRAP_PLATFORM_STATUS; continuing"
  fi
fi

# A CFW platform module may replace PortMaster's default helper without closing
# the live pugwash dialog. The game then runs (including audio/input) behind the
# dialog's black surface. Act only on PortMaster's exact live FIFO and through
# its own close API; unsafe or unprovable ownership fails before game launch.
NXBOOTSTRAP_DIALOG_PIPE=${PM_PIPE:-}
if [ -n "$NXBOOTSTRAP_DIALOG_PIPE" ] && \
   { [ -e "$NXBOOTSTRAP_DIALOG_PIPE" ] || [ -L "$NXBOOTSTRAP_DIALOG_PIPE" ]; }; then
  if [ ! -p "$NXBOOTSTRAP_DIALOG_PIPE" ] || [ -L "$NXBOOTSTRAP_DIALOG_PIPE" ]; then
    echo "ERROR: PortMaster dialog handoff failed: PM_PIPE is not a live non-symlink FIFO"
    nxbootstrap_finish
    exit 1
  fi
  if ! declare -F PortMasterDialogExit >/dev/null 2>&1; then
    echo "ERROR: PortMaster dialog handoff failed: close API unavailable while PM_PIPE is active"
    nxbootstrap_finish
    exit 1
  fi
  if PortMasterDialogExit; then
    :
  else
    NXBOOTSTRAP_PLATFORM_STATUS=$?
    echo "ERROR: PortMaster dialog handoff failed: close API returned status $NXBOOTSTRAP_PLATFORM_STATUS"
    nxbootstrap_finish
    exit 1
  fi
  if [ -e "$NXBOOTSTRAP_DIALOG_PIPE" ] || [ -L "$NXBOOTSTRAP_DIALOG_PIPE" ]; then
    echo "ERROR: PortMaster dialog handoff failed: PM_PIPE remained after close request"
    nxbootstrap_finish
    exit 1
  fi
  echo "PortMaster dialog closed after platform helper"
fi
unset NXBOOTSTRAP_DIALOG_PIPE NXBOOTSTRAP_PLATFORM_STATUS

nxbootstrap_phase_event preflight OK bootstrap 6191 || {
  nxbootstrap_finish
  exit 1
}


# NXExtract owner-data phase (BYO data): runs before the game, other process.
NXDIR=""
[ -f "$GAMEDIR/nxextract/run-extractor.sh" ] && NXDIR="$GAMEDIR/nxextract"
[ -z "$NXDIR" ] && [ -f "$GAMEDIR/run-extractor.sh" ] && NXDIR="$GAMEDIR"
NXEXTRACT_REQUESTED=1
if [ "$NXEXTRACT_REQUESTED" = 1 ]; then
  nxbootstrap_phase_event nxextract START bootstrap 6200 || {
    nxbootstrap_finish
    exit 1
  }
  NXEXTRACT_INCOMPLETE=0
  [ -n "$NXDIR" ] && [ ! -L "$NXDIR" ] || NXEXTRACT_INCOMPLETE=1
  for nxfile in "$GAMEDIR/extractor.json" "$NXDIR/run-extractor.sh" \
    "$NXDIR/nxextract.py" "$NXDIR/nxextract-runtime-env.sh" \
    "$NXDIR/nxextract-ui"; do
    [ -f "$nxfile" ] && [ -s "$nxfile" ] && [ ! -L "$nxfile" ] || NXEXTRACT_INCOMPLETE=1
  done
  if [ "$NXEXTRACT_INCOMPLETE" = 1 ]; then
    echo "ERROR: incomplete NXExtract integration"
    nxbootstrap_phase_event nxextract ERROR bootstrap 6202 || true
    nxbootstrap_finish
    exit 1
  fi
  $ESUDO chmod +x "$NXDIR/nxextract-ui" 2>/dev/null || true
  if [ ! -x "$NXDIR/nxextract-ui" ]; then
    echo "ERROR: mandatory NXExtract UI is not executable"
    nxbootstrap_phase_event nxextract ERROR bootstrap 6202 || true
    nxbootstrap_finish
    exit 1
  fi
  NXEXTRACT_RESULT_FILE="$GAMEDIR/nxextract-result.json"
  if [ -e "$NXEXTRACT_RESULT_FILE" ] || [ -L "$NXEXTRACT_RESULT_FILE" ]; then
    if [ ! -f "$NXEXTRACT_RESULT_FILE" ] || [ -L "$NXEXTRACT_RESULT_FILE" ]; then
      echo "ERROR: stale NXExtract result path is unsafe"
      nxbootstrap_phase_event nxextract ERROR bootstrap 6202 || true
      nxbootstrap_finish
      exit 1
    fi
    mv -f "$NXEXTRACT_RESULT_FILE" \
      "$GAMEDIR/nxextract-result.prev.json" || {
        echo "ERROR: could not rotate the previous NXExtract result"
        nxbootstrap_phase_event nxextract ERROR bootstrap 6202 || true
        nxbootstrap_finish
        exit 1
      }
  fi
  # The firmware python3 must start: a corrupted stdlib bytecode cache (muOS,
  # "bad marshal data" in encodings) kills it before NXExtract sees the APK.
  # Retry with a private cache, then fail loudly instead of "result malformed".
  NXEXTRACT_PY_PROBE='import encodings, json, zipfile, hashlib'
  if ! python3 -B -c "$NXEXTRACT_PY_PROBE" >/dev/null 2>&1; then
    if PYTHONPYCACHEPREFIX="$GAMEDIR/.nxpycache" python3 -B -c "$NXEXTRACT_PY_PROBE" >/dev/null 2>&1; then
      export PYTHONPYCACHEPREFIX="$GAMEDIR/.nxpycache"
      echo "WARN: system python bytecode cache is broken; using $GAMEDIR/.nxpycache"
    else
      echo "ERROR: the firmware's python3 cannot start (corrupted stdlib/bytecode);"
      echo "ERROR: NXExtract needs a working python3 -- reinstall/update the CFW."
      nxbootstrap_phase_event nxextract ERROR bootstrap 6209 || true
      nxbootstrap_finish
      exit 1
    fi
  fi
  NXEXTRACT_STATUS=0
  NXEXTRACT_GAME_DIR="$GAMEDIR" \
    bash "$NXDIR/nxextract-runtime-env.sh" \
    bash "$NXDIR/run-extractor.sh" || NXEXTRACT_STATUS=$?
  NXEXTRACT_RESULT_STATUS=0
  NXEXTRACT_SUMMARY=""
  if [ -f "$NXEXTRACT_RESULT_FILE" ] && [ ! -L "$NXEXTRACT_RESULT_FILE" ]; then
    if NXEXTRACT_SUMMARY=$(nxbootstrap_validate_nxextract_result \
      "$NXEXTRACT_RESULT_FILE" "$NXEXTRACT_STATUS"); then
      :
    else
      NXEXTRACT_RESULT_STATUS=$?
    fi
  else
    NXEXTRACT_RESULT_STATUS=1
  fi
  if [ "$NXEXTRACT_RESULT_STATUS" -ne 0 ]; then
    echo "ERROR: NXExtract terminal result is missing, unsafe or malformed"
    nxbootstrap_phase_event nxextract ERROR bootstrap 6202 \
      "$NXEXTRACT_STATUS" || true
    nxbootstrap_finish
    if [ "$NXEXTRACT_STATUS" -ne 0 ]; then exit "$NXEXTRACT_STATUS"; fi
    exit 1
  fi
  printf 'NXEXTRACT_RESULT %s\n' "$NXEXTRACT_SUMMARY"
  if [ "$NXEXTRACT_STATUS" -ne 0 ]; then
    echo "ERROR: game data installation did not complete"
    nxbootstrap_phase_event nxextract ERROR extractor 6203 \
      "$NXEXTRACT_STATUS" || true
    nxbootstrap_finish
    exit "$NXEXTRACT_STATUS"
  fi
  nxbootstrap_phase_event nxextract OK extractor 6201 || {
    nxbootstrap_finish
    exit 1
  }
fi
unset NXDIR NXEXTRACT_REQUESTED NXEXTRACT_INCOMPLETE nxfile \
  NXEXTRACT_RESULT_FILE NXEXTRACT_STATUS NXEXTRACT_RESULT_STATUS \
  NXEXTRACT_SUMMARY

# Manifest-owned payload gate: extraction/prepare must finish before launch.
NXBOOTSTRAP_REQUIRED_FILES='offtheroad
nxsplash-nextos
lib/libgame.so
lib/libc++_shared.so'
while IFS= read -r required_file; do
  [ -n "$required_file" ] || continue
  required_path=$(readlink -f "$GAMEDIR/$required_file" 2>/dev/null) || required_path=""
  case "$required_path" in
    "$GAMEDIR"/*) ;;
    *) required_path="" ;;
  esac
  if [ -z "$required_path" ] || [ ! -f "$required_path" ] || \
     [ ! -s "$required_path" ] || [ -L "$GAMEDIR/$required_file" ]; then
    echo "ERROR: required file is missing or unsafe: $required_file"
    nxbootstrap_finish
    exit 1
  fi
done <<< "$NXBOOTSTRAP_REQUIRED_FILES"
unset NXBOOTSTRAP_REQUIRED_FILES required_file required_path


# Mandatory framework identity handoff: data is complete, native lifecycle has
# not started, and no game-private library path has been added by nxbootstrap.
NXBOOTSTRAP_SPLASH="$GAMEDIR/nxsplash-nextos"
NXBOOTSTRAP_SPLASH_LIBS=""
for d in "$controlfolder/libs" "$controlfolder/libs.aarch64" \
  /usr/local/lib/aarch64-linux-gnu /usr/local/lib64 /usr/local/lib \
  /usr/lib/aarch64-linux-gnu /lib/aarch64-linux-gnu \
  /usr/lib64 /lib64 /usr/lib /lib; do
  [ -n "$d" ] && [ -d "$d" ] && \
    NXBOOTSTRAP_SPLASH_LIBS="${NXBOOTSTRAP_SPLASH_LIBS:+$NXBOOTSTRAP_SPLASH_LIBS:}$d"
done
echo "nxsplash 0.1.2: mandatory handoff begin"
nxbootstrap_phase_event nxsplash START bootstrap 6204 || {
  nxbootstrap_finish
  exit 1
}
# 0.6.23: em CFW 64-bit-only com o loader ARMHF fora do caminho, TODO ELF
# empacotado precisa do mesmo prefixo que o jogo — o splash executado direto
# morria com o falso "No such file or directory" (status 127) que o proprio
# preflight explica (caso de campo: spruce/Miyoo Flip).
NXBOOTSTRAP_SPLASH_PREFIX=""
if [ -n "${NXBOOTSTRAP_INTERP_PREFIX:-}" ]; then
  NXBOOTSTRAP_SPLASH_INTERP=$(LC_ALL=C grep -a -o -m1 -E '/lib(32|64)?/ld-[A-Za-z0-9._-]*\.so[A-Za-z0-9._-]*' "$NXBOOTSTRAP_SPLASH" 2>/dev/null | head -n1)
  if [ -n "$NXBOOTSTRAP_SPLASH_INTERP" ] && [ ! -e "$NXBOOTSTRAP_SPLASH_INTERP" ]; then
    NXBOOTSTRAP_SPLASH_PREFIX="$NXBOOTSTRAP_INTERP_PREFIX"
    echo "NOTE: nxsplash also runs through the alternate dynamic loader."
  fi
fi
if NX_SPLASH_TTY="${CUR_TTY:-}" \
   LD_LIBRARY_PATH="$NXBOOTSTRAP_SPLASH_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
   $NXBOOTSTRAP_SPLASH_PREFIX "$NXBOOTSTRAP_SPLASH" 'Off The Road'; then
  echo "nxsplash 0.1.2: mandatory handoff complete"
  nxbootstrap_phase_event nxsplash OK bootstrap 6205 || {
    nxbootstrap_finish
    exit 1
  }
else
  NXBOOTSTRAP_SPLASH_STATUS=$?
  echo "ERROR: mandatory nxsplash failed status=$NXBOOTSTRAP_SPLASH_STATUS"
  nxbootstrap_phase_event nxsplash ERROR bootstrap 6206 \
    "$NXBOOTSTRAP_SPLASH_STATUS" || true
  nxbootstrap_finish
  exit "$NXBOOTSTRAP_SPLASH_STATUS"
fi
unset NXBOOTSTRAP_SPLASH NXBOOTSTRAP_SPLASH_LIBS NXBOOTSTRAP_SPLASH_STATUS \
  NXBOOTSTRAP_SPLASH_PREFIX NXBOOTSTRAP_SPLASH_INTERP d
# Saves and configuration stay inside the port directory.
export HOME="$GAMEDIR"
# An empty CFW mapping must not clobber a valid inherited one (contract:
# honor the existing mapping and only log when the CFW publishes nothing).
# V3-CONTROLLERS-01 / V3-SETTINGS-01 (blocker 4): materialize the owner's
# editable copies from the immutable defaults exactly once, ATOMICALLY and
# symlink-safe on the target, the .new candidate AND the receipt/pin. An
# edited copy is NEVER overwritten; an untouched copy migrates with a receipt;
# a customized copy receives the new default as a side-by-side ".new". Every
# write goes through nxbootstrap_atomic_install so a planted symlink at the
# destination or the temp path can never be followed, and an interruption
# always leaves the last valid configuration in place.
nxbootstrap_atomic_install() {
  # $1 source (regular, non-symlink)  $2 destination path
  local src=$1 dest=$2 dir base tmp
  [ -f "$src" ] && [ ! -L "$src" ] || return 1
  dir=$(dirname -- "$dest")
  [ -d "$dir" ] && [ ! -L "$dir" ] || return 1
  base=$(basename -- "$dest")
  tmp="$dir/.$base.nxtmp.$$.$RANDOM"
  # Create AND fill $tmp in ONE exclusive open: set -C makes the shell open the
  # redirect with O_CREAT|O_EXCL, which fails on any pre-existing path INCLUDING
  # a symlink (dangling or not), so a planted symlink is refused instead of
  # written through. The bytes go to that same descriptor -- there is no
  # close/reopen window to race, which was the TOCTOU in the earlier
  # ": > tmp" (create empty) then "cat > tmp" (reopen, unguarded) sequence.
  if ! ( umask 077; set -C; cat "$src" > "$tmp" ) 2>/dev/null; then
    rm -f "$tmp" 2>/dev/null; return 1
  fi
  chmod 0644 "$tmp" 2>/dev/null || true
  # mv replaces the destination inode (never writes through a symlinked dest).
  if mv -f "$tmp" "$dest" 2>/dev/null; then return 0; fi
  rm -f "$tmp" 2>/dev/null; return 1
}
nxbootstrap_atomic_write_line() {
  # $1 literal line  $2 destination path (pin/receipt) -- atomic, symlink-safe
  local line=$1 dest=$2 dir base tmp
  dir=$(dirname -- "$dest")
  [ -d "$dir" ] && [ ! -L "$dir" ] || return 1
  base=$(basename -- "$dest")
  tmp="$dir/.$base.nxtmp.$$.$RANDOM"
  ( umask 077; set -C; printf '%s\n' "$line" > "$tmp" ) 2>/dev/null || { rm -f "$tmp" 2>/dev/null; return 1; }
  if [ -L "$tmp" ]; then rm -f "$tmp" 2>/dev/null; return 1; fi
  mv -f "$tmp" "$dest" 2>/dev/null || { rm -f "$tmp" 2>/dev/null; return 1; }
}
for nxbootstrap_mutable in NEXTOSCONTROLLERS.gptk NEXTOSSETTINGS.txt; do
  nxbootstrap_default="$GAMEDIR/defaults/$nxbootstrap_mutable"
  nxbootstrap_target="$GAMEDIR/$nxbootstrap_mutable"
  [ -f "$nxbootstrap_default" ] && [ ! -L "$nxbootstrap_default" ] || continue
  nxbootstrap_default_pin="$GAMEDIR/.nxruntime/$nxbootstrap_mutable.default.sha256"
  if [ ! -e "$nxbootstrap_target" ] && [ ! -L "$nxbootstrap_target" ]; then
    if nxbootstrap_atomic_install "$nxbootstrap_default" "$nxbootstrap_target"; then
      echo "OWNER FILE: materialized $nxbootstrap_mutable from defaults/"
    fi
    if command -v sha256sum >/dev/null 2>&1; then
      [ -d "$GAMEDIR/.nxruntime" ] || ( umask 077; mkdir "$GAMEDIR/.nxruntime" ) 2>/dev/null || true
      nxbootstrap_hash=$(sha256sum "$nxbootstrap_default" 2>/dev/null); nxbootstrap_hash=${nxbootstrap_hash%% *}
      [ -n "$nxbootstrap_hash" ] && nxbootstrap_atomic_write_line "$nxbootstrap_hash" "$nxbootstrap_default_pin" || true
    fi
  elif [ -f "$nxbootstrap_target" ] && [ ! -L "$nxbootstrap_target" ] && \
       command -v sha256sum >/dev/null 2>&1 && [ -f "$nxbootstrap_default_pin" ] && \
       [ ! -L "$nxbootstrap_default_pin" ]; then
    read -r nxbootstrap_previous_default < "$nxbootstrap_default_pin" || nxbootstrap_previous_default=""
    nxbootstrap_current_default=$(sha256sum "$nxbootstrap_default" 2>/dev/null)
    nxbootstrap_current_default=${nxbootstrap_current_default%% *}
    if [ -n "$nxbootstrap_previous_default" ] && \
       [ "$nxbootstrap_current_default" != "$nxbootstrap_previous_default" ]; then
      nxbootstrap_owner_hash=$(sha256sum "$nxbootstrap_target" 2>/dev/null)
      nxbootstrap_owner_hash=${nxbootstrap_owner_hash%% *}
      if [ "$nxbootstrap_owner_hash" = "$nxbootstrap_previous_default" ]; then
        if nxbootstrap_atomic_install "$nxbootstrap_default" "$nxbootstrap_target"; then
          nxbootstrap_atomic_write_line "$nxbootstrap_current_default" "$nxbootstrap_default_pin" || true
          echo "OWNER FILE: $nxbootstrap_mutable was untouched; migrated to the new default (receipt)"
        fi
      elif [ ! -e "$nxbootstrap_target.new" ] && [ ! -L "$nxbootstrap_target.new" ]; then
        if nxbootstrap_atomic_install "$nxbootstrap_default" "$nxbootstrap_target.new"; then
          echo "OWNER FILE: $nxbootstrap_mutable is customized; new default saved as $nxbootstrap_mutable.new"
        fi
      fi
    fi
  fi
done

[ -n "$sdl_controllerconfig" ] && export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"

# Optional per-port adapter: may export env or replace $BIN / $BIN_PRELOAD.
readonly NXBOOTSTRAP_ANALOG_STICKS_HINT
[ -f "$GAMEDIR/port-env.sh" ] && [ ! -L "$GAMEDIR/port-env.sh" ] && . "$GAMEDIR/port-env.sh"

# Host phase ends here: game/private library paths must never contaminate
# pm_platform_helper or the setup tools above, so they enter only now.
# Firmware/PortMaster overlays first; preserve distro-local providers before
# the system defaults, then append the game's own directory.
LIBS=""
for d in "$controlfolder/libs" "$controlfolder/libs.aarch64" \
         /usr/local/lib/aarch64-linux-gnu /usr/local/lib64 /usr/local/lib \
         /usr/lib/aarch64-linux-gnu /lib/aarch64-linux-gnu \
         /usr/lib64 /lib64 /usr/lib /lib; do
  [ -n "$d" ] && [ -d "$d" ] && LIBS="${LIBS:+$LIBS:}$d"
done
export LD_LIBRARY_PATH="${LIBS}:$GAMEDIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
nxbootstrap_install_exit_trap
nxbootstrap_install_early_traps

# Manifest-owned runtime contract: reassert after every mutable shell hook.
# Reassert after the mutable adapter hook; adapters consume, never redefine it.
NXPORT_LANGUAGE=$NXBOOTSTRAP_LANGUAGE
export NXPORT_LANGUAGE

case "$NXBOOTSTRAP_ANALOG_STICKS_HINT" in
  0|1|2) export NXINPUT_ANALOG_STICKS_HINT="$NXBOOTSTRAP_ANALOG_STICKS_HINT" ;;
  *) unset NXINPUT_ANALOG_STICKS_HINT ;;
esac
export NXCOMPAT_PORT_ID=offtheroad
# The guest's lexical identity is the LOGICAL root it was invoked under
# (V3-UPDATE-01); the physical root stays available for framework-side I/O.
# Both resolve to the same inode (proven by the two-tree -ef guard above).
export NXCOMPAT_GAME_DIR="$NXBOOTSTRAP_LOGICAL_GAMEDIR"
export NXCOMPAT_GAME_DIR_PHYSICAL="$NXBOOTSTRAP_PHYSICAL_GAMEDIR"
export NXCOMPAT_REQUIRED_CAPABILITIES='host.portmaster
graphics.window
graphics.gles2
graphics.egl
graphics.egl-config
graphics.drawable
audio.output-open
input.controller-mapping
input.controller-api
audio.embedded-openal'
export NXCOMPAT_ENABLED_QUIRKS=''
export NXCOMPAT_RUNTIME_REPORT=log

# Guest audio shield (capability-gated, additive): a port whose APK bundles the
# Android OpenAL-soft reads the HOST's /etc/openal/alsoft.conf too. A CFW that
# ships a native `drivers=` line there (AmberELEC ships drivers=alsa) leaves the
# embedded OpenAL with no matching backend -> the game goes SILENT with no error
# (field case: Tightrope on AmberELEC/P4ELEC; reproduced and fix-proven live on
# dArkOSRE by planting that exact file). Pinning ALSOFT_DRIVERS to the OpenSL
# bridge the loader provides neutralizes only that lethal option. Every port
# without the capability keeps a byte-identical environment.
for NXBOOTSTRAP_CAP in $NXCOMPAT_REQUIRED_CAPABILITIES; do
  [ "$NXBOOTSTRAP_CAP" = audio.embedded-openal ] || continue
  export ALSOFT_DRIVERS=opensl
  echo "AUDIO GUEST: ALSOFT_DRIVERS=opensl pinned (embedded OpenAL; host alsoft.conf neutralized)"
  break
done
unset NXBOOTSTRAP_CAP
# One-line receipt of the inherited audio-relevant environment: when a device
# mutes a guest, this line names the suspects without a second round-trip.
echo "ENV RECEIPT: sdl_audiodriver=${SDL_AUDIODRIVER:-} alsoft_drivers=${ALSOFT_DRIVERS:-} alsoft_conf=${ALSOFT_CONF:-} pulse_server=${PULSE_SERVER:-} xdg_runtime_dir=${XDG_RUNTIME_DIR:-}"

game_pid=
NXBOOTSTRAP_CHILD_STARTTIME=
NXBOOTSTRAP_SHUTDOWN_REQUESTED=0
NXBOOTSTRAP_TERM_SENT=0
NXBOOTSTRAP_SIGNAL_COUNT=0
nxbootstrap_capture_child_starttime() {
  local child_stat child_rest
  case "$game_pid" in ''|*[!0-9]*) return 1 ;; esac
  IFS= read -r child_stat < "/proc/$game_pid/stat" 2>/dev/null || return 1
  child_rest=${child_stat##*) }
  set -- $child_rest
  [ "$#" -ge 20 ] || return 1
  NXBOOTSTRAP_CHILD_STARTTIME=${20}
}
nxbootstrap_child_alive() {
  local child_stat child_rest child_state child_start
  case "$game_pid" in ''|*[!0-9]*) return 1 ;; esac
  [ -n "$NXBOOTSTRAP_CHILD_STARTTIME" ] || return 1
  builtin kill -0 "$game_pid" 2>/dev/null || return 1
  IFS= read -r child_stat < "/proc/$game_pid/stat" 2>/dev/null || return 1
  child_rest=${child_stat##*) }
  set -- $child_rest
  [ "$#" -ge 20 ] || return 1
  child_state=$1
  child_start=${20}
  case "$child_state" in Z|X) return 1 ;; esac
  [ "$child_start" = "$NXBOOTSTRAP_CHILD_STARTTIME" ]
}
nxbootstrap_signal_child() {
  [ "$NXBOOTSTRAP_TERM_SENT" = 0 ] || return 0
  [ -n "$NXBOOTSTRAP_CHILD_STARTTIME" ] || \
    nxbootstrap_capture_child_starttime || return 0
  nxbootstrap_child_alive || return 0
  NXBOOTSTRAP_TERM_SENT=1
  builtin kill -TERM "$game_pid" 2>/dev/null || true
}
nxbootstrap_request_shutdown() {
  NXBOOTSTRAP_SIGNAL_COUNT=$((NXBOOTSTRAP_SIGNAL_COUNT + 1))
  if [ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 0 ]; then
    NXBOOTSTRAP_SHUTDOWN_REQUESTED=1
  fi
  nxbootstrap_signal_child || true
}
trap nxbootstrap_request_shutdown INT TERM HUP
# Close the lock fd IN THE CHILD ONLY (9>&-): the launcher keeps fd 9 and the
# flock for the whole game, but the game — and any detached helper it forks —
# must not inherit the lock, or an orphaned grandchild would hold the port lock
# after the launcher exits and block the next launch.
nxbootstrap_phase_event runtime START lifecycle 6207 || {
  nxbootstrap_finish
  exit 1
}
if [ -n "$BIN_PRELOAD" ]; then
  LD_PRELOAD="$BIN_PRELOAD${LD_PRELOAD:+:$LD_PRELOAD}" $NXBOOTSTRAP_INTERP_PREFIX "$BIN" 9>&- &
else
  $NXBOOTSTRAP_INTERP_PREFIX "$BIN" 9>&- &
fi
game_pid=$!
nxbootstrap_capture_child_starttime || NXBOOTSTRAP_CHILD_STARTTIME=""
[ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 0 ] || nxbootstrap_signal_child
if wait "$game_pid"; then status=0; else status=$?; fi
if [ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 1 ]; then
  trap '' INT TERM HUP
  NXBOOTSTRAP_SHUTDOWN_TICKS=10
  while [ "$NXBOOTSTRAP_SHUTDOWN_TICKS" -gt 0 ] && nxbootstrap_child_alive; do
    sleep 1 || true
    NXBOOTSTRAP_SHUTDOWN_TICKS=$((NXBOOTSTRAP_SHUTDOWN_TICKS - 1))
  done
  if nxbootstrap_child_alive; then
    echo "== termination deadline expired; sending KILL =="
    builtin kill -KILL "$game_pid" 2>/dev/null || true
  fi
  # Each handled frontend signal can contribute one synthetic 128+n result.
  NXBOOTSTRAP_REWAIT_BUDGET=$NXBOOTSTRAP_SIGNAL_COUNT
  while [ "$NXBOOTSTRAP_REWAIT_BUDGET" -gt 0 ]; do
    case "$status" in 129|130|143) ;; *) break ;; esac
    NXBOOTSTRAP_REWAIT_BUDGET=$((NXBOOTSTRAP_REWAIT_BUDGET - 1))
    if wait "$game_pid" 2>/dev/null; then status=0; else status=$?; fi
  done
else
  # 128+n can also be wait itself being interrupted; recover the child truth.
  while [ "$status" -gt 128 ] && nxbootstrap_child_alive; do
    if wait "$game_pid"; then status=0; else status=$?; fi
  done
fi
nxbootstrap_phase_event runtime EXIT lifecycle 6208 "$status" || \
  echo "WARNING: runtime exit boundary could not be persisted"

# V3-ROLLBACK-01: health proof. Only an exact receipt from THIS run and THIS
# generation can promote pending -> active. It is read through an opened fd and
# checked for owner/mode/inode/link-count before its canonical JSON is trusted.
nxbootstrap_health_receipt_valid() {
  local expected line extra health_meta health_mode health_links
  [ -n "${NXBOOTSTRAP_HEALTH_FILE:-}" ] || return 1
  [ -f "$NXBOOTSTRAP_HEALTH_FILE" ] && [ ! -L "$NXBOOTSTRAP_HEALTH_FILE" ] && \
    [ -O "$NXBOOTSTRAP_HEALTH_FILE" ] || return 1
  { exec 8<"$NXBOOTSTRAP_HEALTH_FILE"; } 2>/dev/null || return 1
  health_meta=()
  IFS=' ' read -r -a health_meta \
    <<< "$(LC_ALL=C command ls -Lldn /proc/self/fd/8 2>/dev/null)"
  health_mode=${health_meta[0]:-}
  health_links=${health_meta[1]:-}
  if [ "$health_mode" != "-rw-------" ] || [ "$health_links" != 1 ] || \
     ! [ "$NXBOOTSTRAP_HEALTH_FILE" -ef /proc/self/fd/8 ]; then
    { exec 8<&-; } 2>/dev/null || true
    return 1
  fi
  IFS= read -r line <&8 || {
    { exec 8<&-; } 2>/dev/null || true
    return 1
  }
  if IFS= read -r extra <&8; then
    { exec 8<&-; } 2>/dev/null || true
    return 1
  fi
  { exec 8<&-; } 2>/dev/null || true
  expected="{\"schema\":\"$NXBOOTSTRAP_HEALTH_SCHEMA\",\"schema_version\":$NXBOOTSTRAP_HEALTH_SCHEMA_VERSION,\"run_id\":\"$NXBOOTSTRAP_HEALTH_RUN_ID\",\"generation\":\"$NXBOOTSTRAP_HEALTH_GENERATION\",\"port_id\":\"$NXBOOTSTRAP_HEALTH_PORT_ID\",\"status\":\"ready\"}"
  [ "$line" = "$expected" ]
}
if [ -n "${NXBOOTSTRAP_SELECTED_GENERATION:-}" ]; then
  nxbootstrap_state_active=$(nxbootstrap_state_field active)
  nxbootstrap_state_pending=$(nxbootstrap_state_field pending)
  nxbootstrap_state_previous=$(nxbootstrap_state_field previous_healthy)
  nxbootstrap_state_seq=$(nxbootstrap_state_field activation_seq)
  nxbootstrap_state_failures=$(nxbootstrap_state_field prehealth_failures)
  nxbootstrap_state_last_health_run=$(nxbootstrap_state_field last_health_run_id)
  case "$nxbootstrap_state_seq" in ''|*[!0-9]*) nxbootstrap_state_seq=0 ;; esac
  case "$nxbootstrap_state_failures" in ''|*[!0-9]*) nxbootstrap_state_failures=0 ;; esac
  nxbootstrap_generation_id_valid "$nxbootstrap_state_active" || nxbootstrap_state_active=null
  nxbootstrap_generation_id_valid "$nxbootstrap_state_pending" || nxbootstrap_state_pending=null
  nxbootstrap_generation_id_valid "$nxbootstrap_state_previous" || nxbootstrap_state_previous=null
  if nxbootstrap_health_receipt_valid; then
    if [ "$nxbootstrap_state_pending" = "$NXBOOTSTRAP_SELECTED_GENERATION" ]; then
      # The formerly active generation becomes the rollback anchor only now,
      # when the new generation has actually proved healthy.
      if [ "$nxbootstrap_state_active" != null ] && \
         nxbootstrap_generation_complete "$NXRUNTIME_DIR/generations/$nxbootstrap_state_active"; then
        nxbootstrap_state_previous=$nxbootstrap_state_active
      fi
      nxbootstrap_state_active=$NXBOOTSTRAP_SELECTED_GENERATION
      nxbootstrap_state_pending=null
    fi
    nxbootstrap_write_state "$NXBOOTSTRAP_SELECTED_GENERATION" \
      "${nxbootstrap_state_pending:-null}" \
      "${nxbootstrap_state_previous:-null}" "$nxbootstrap_state_seq" 0 \
      "null" "$NXOBS_RUN_ID" || true
    nxbootstrap_update_event NXU0006 "generation $NXBOOTSTRAP_SELECTED_GENERATION proved healthy receipt_run=$NXOBS_RUN_ID"
  elif [ "$nxbootstrap_state_pending" = "$NXBOOTSTRAP_SELECTED_GENERATION" ]; then
    nxbootstrap_state_failures=$((nxbootstrap_state_failures + 1))
    nxbootstrap_write_state "${nxbootstrap_state_active:-null}" \
      "$nxbootstrap_state_pending" "${nxbootstrap_state_previous:-null}" \
      "$nxbootstrap_state_seq" "$nxbootstrap_state_failures" \
      "$NXBOOTSTRAP_SELECTED_GENERATION" \
      "${nxbootstrap_state_last_health_run:-null}" || true
    nxbootstrap_update_event NXU0005 "no valid run-bound health receipt for pending generation $NXBOOTSTRAP_SELECTED_GENERATION; prehealth_failures=$nxbootstrap_state_failures"
  else
    nxbootstrap_update_event NXU0007 "stable generation $NXBOOTSTRAP_SELECTED_GENERATION produced no valid health receipt; active state unchanged"
  fi
  rm -f -- "$NXBOOTSTRAP_HEALTH_FILE" 2>/dev/null || true
fi

# RUNTIME DIAGNOSIS: turn a bare exit code + black screen into one readable
# verdict in the log. Signatures are read from this same log; a clean exit or a
# frontend chord (SIGTERM/SIGKILL) is NOT an error. Never alters $status.
NXBOOTSTRAP_LOG="$GAMEDIR/log.txt"
nxbootstrap_log_has() { [ -r "$NXBOOTSTRAP_LOG" ] && LC_ALL=C grep -qaE "$1" "$NXBOOTSTRAP_LOG" 2>/dev/null; }
NXBOOTSTRAP_DIAG="unclassified — see the log above"
if nxbootstrap_log_has 'undefined symbol:'; then
  NXBOOTSTRAP_DIAG="undefined-symbol — the loader needs a symbol the device library does not export; rebuild against the device SDK ($(LC_ALL=C grep -aoE 'undefined symbol: [A-Za-z0-9_]+' "$NXBOOTSTRAP_LOG" 2>/dev/null | head -n1))"
elif nxbootstrap_log_has 'cannot open shared object'; then
  NXBOOTSTRAP_DIAG="missing-library — a required .so is absent on this CFW; bundle it in the port ($(LC_ALL=C grep -aoE '[A-Za-z0-9._+-]+\.so[A-Za-z0-9._]*: cannot open shared object' "$NXBOOTSTRAP_LOG" 2>/dev/null | head -n1))"
elif [ "$status" = 127 ]; then
  NXBOOTSTRAP_DIAG="status-127 — the executable or its dynamic loader could not be run (missing interpreter/library)"
elif [ "$status" = 139 ]; then
  NXBOOTSTRAP_DIAG="crash-SIGSEGV — the game hit a segfault; read the last frames above for the failing call"
elif [ "$status" = 134 ]; then
  NXBOOTSTRAP_DIAG="crash-SIGABRT — the game aborted itself (assert/abort); the message above names the reason"
elif [ "$status" = 132 ]; then
  NXBOOTSTRAP_DIAG="crash-SIGILL — illegal instruction, usually a wrong-arch or bad-codegen build"
elif nxbootstrap_log_has 'frame proof verdict=(black|absent)' || \
     { nxbootstrap_log_has 'frame proof' && ! nxbootstrap_log_has 'frame proof verdict=OK'; }; then
  NXBOOTSTRAP_DIAG="black-screen — the process ran but no non-black frame was observed; check EGL/GL context and the video receipt above"
elif [ "$status" = 0 ] || [ "$status" = 143 ] || [ "$status" = 137 ] || [ "$status" = 130 ]; then
  NXBOOTSTRAP_DIAG="clean — exited normally or via the frontend/exit chord (status $status)"
else
  NXBOOTSTRAP_DIAG="nonzero-exit (status $status) — the game returned an error; read the log above"
fi
echo "RUNTIME DIAGNOSIS: $NXBOOTSTRAP_DIAG"
# SUPPORT block: everything a maintainer needs in the ONE file the player
# already sends. No owner path, no address, no player data.
echo "== SUPPORT =="
echo "port=offtheroad version=$(LC_ALL=C head -c 32 "$GAMEDIR/version.txt" 2>/dev/null | tr -d "[:space:]") launcher=0.6.32 cfw=${CFW_NAME:-none}"
if [ -r "$GAMEDIR/nxextract-version.txt" ]; then
  echo "nxextract=$(LC_ALL=C head -c 32 "$GAMEDIR/nxextract-version.txt" 2>/dev/null | tr -d '[:space:]')"
fi
LC_ALL=C grep -am1 '"schema":"org.nextos.nxextract.terminal-result"' \
  "$GAMEDIR/log.txt" 2>/dev/null | head -c 2048 || true
echo "files-to-send=log.txt log.prev.txt log.prev2.txt nxextract.log events.jsonl"
echo "== end (status $status) =="

# The game may leave the console keymap off (K_OFF); reset before handing back.
[ -n "$CUR_TTY" ] && [ -c "$CUR_TTY" ] && printf '\033c' > "$CUR_TTY" 2>/dev/null
nxbootstrap_finish
exit $status
